<a href="https://colab.research.google.com/github/arnavon2005/Army_Provost_ML_Project/blob/main/09_Response_Team_Resource_Allocation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ======================================================================
# ARMY PROVOST ML PROJECT
# NOTEBOOK 09 — RESPONSE TEAM RESOURCE ALLOCATION
# ======================================================================

from google.colab import drive
import os
from pathlib import Path

# Mount Google Drive
drive.mount('/content/drive')

# ----------------------------------------------------------------------
# Fixed Project Paths
# ----------------------------------------------------------------------

PROJECT_ROOT = Path("/content/drive/MyDrive/Army_Provost_ML_Project")

DATASETS_DIR = PROJECT_ROOT / "Datasets"
RAW_DATA_DIR = DATASETS_DIR / "Raw"
CLEANED_DATA_DIR = DATASETS_DIR / "Cleaned"

NOTEBOOKS_DIR = PROJECT_ROOT / "Notebooks"
MODELS_DIR = PROJECT_ROOT / "Models"
FIGURES_DIR = PROJECT_ROOT / "Figures"
REPORTS_DIR = PROJECT_ROOT / "Reports"
OUTPUTS_DIR = PROJECT_ROOT / "Outputs"
LOGS_DIR = PROJECT_ROOT / "Logs"

# Existing DSS / ML artifacts
RF_MODEL_PATH = MODELS_DIR / "final_random_forest.pkl"
PREPROCESSOR_PATH = MODELS_DIR / "preprocessing_pipeline.pkl"

DSS_BACKEND_PATH = OUTPUTS_DIR / "army_provost_dss_backend.py"

# Future resource-allocation artifacts
RESPONSE_TEAM_REGISTRY_PATH = OUTPUTS_DIR / "Response_Team_Registry.csv"
RESOURCE_ALLOCATION_BACKEND_PATH = OUTPUTS_DIR / "response_team_allocation_backend.py"

# ----------------------------------------------------------------------
# Notebook Responsibility
# ----------------------------------------------------------------------

print("=" * 70)
print("ARMY PROVOST ML PROJECT")
print("NOTEBOOK 09 — RESPONSE TEAM RESOURCE ALLOCATION")
print("=" * 70)

print("\nProject Root:")
print(PROJECT_ROOT)

print("\nNotebook Responsibility:")
print("1. Define synthetic Response Team Registry")
print("2. Map operational response categories to required capabilities")
print("3. Evaluate team availability and readiness")
print("4. Rank suitable response teams transparently")
print("5. Recommend primary and alternate resources")
print("6. Support later human confirmation / override")
print("7. Generate reusable resource-allocation backend")

print("\nExisting Intelligence Layer:")
print("Random Forest Model :", RF_MODEL_PATH)
print("Preprocessor        :", PREPROCESSOR_PATH)
print("DSS Backend         :", DSS_BACKEND_PATH)

print("\nPlanned Resource Layer:")
print("Team Registry       :", RESPONSE_TEAM_REGISTRY_PATH)
print("Allocation Backend  :", RESOURCE_ALLOCATION_BACKEND_PATH)

print("\nIMPORTANT:")
print("- Existing ML models will NOT be retrained.")
print("- Existing DSS operational mapping will be reused.")
print("- Response-team information will be synthetic.")
print("- Final deployment authority remains with the human operator.")

print("\n" + "=" * 70)
print("NOTEBOOK INITIALIZATION COMPLETE")
print("=" * 70)

Mounted at /content/drive
======================================================================
ARMY PROVOST ML PROJECT
NOTEBOOK 09 — RESPONSE TEAM RESOURCE ALLOCATION
======================================================================

Project Root:
/content/drive/MyDrive/Army_Provost_ML_Project

Notebook Responsibility:
1. Define synthetic Response Team Registry
2. Map operational response categories to required capabilities
3. Evaluate team availability and readiness
4. Rank suitable response teams transparently
5. Recommend primary and alternate resources
6. Support later human confirmation / override
7. Generate reusable resource-allocation backend

Existing Intelligence Layer:
Random Forest Model : /content/drive/MyDrive/Army_Provost_ML_Project/Models/final_random_forest.pkl
Preprocessor        : /content/drive/MyDrive/Army_Provost_ML_Project/Models/preprocessing_pipeline.pkl
DSS Backend         : /content/drive/MyDrive/Army_Provost_ML_Project/Outputs/army_provost_dss_backend.py

Planned Resource Layer:
Team Registry       : /content/drive/MyDrive/Army_Provost_ML_Project/Outputs/Response_Team_Registry.csv
Allocation Backend  : /content/drive/MyDrive/Army_Provost_ML_Project/Outputs/response_team_allocation_backend.py

IMPORTANT:
- Existing ML models will NOT be retrained.
- Existing DSS operational mapping will be reused.
- Response-team information will be synthetic.
- Final deployment authority remains with the human operator.

======================================================================
NOTEBOOK INITIALIZATION COMPLETE
======================================================================

In [2]:
# ======================================================================
# STEP 2 — RESPONSE TEAM REGISTRY SCHEMA DEFINITION
# ======================================================================

import pandas as pd

# ----------------------------------------------------------------------
# Response Team Registry Schema
# ----------------------------------------------------------------------

response_team_schema = [
    {
        "Field": "Team_ID",
        "Type": "String",
        "Example": "RT-01",
        "Purpose": "Unique identifier for each synthetic response team"
    },
    {
        "Field": "Team_Name",
        "Type": "String",
        "Example": "Response Team 01",
        "Purpose": "Operator-friendly team name"
    },
    {
        "Field": "Status",
        "Type": "Category",
        "Example": "AVAILABLE",
        "Purpose": "Current deployment availability: AVAILABLE, ASSIGNED, or OFFLINE"
    },
    {
        "Field": "Current_Zone",
        "Type": "Category",
        "Example": "Zone B",
        "Purpose": "Current fictional operational zone of the team"
    },
    {
        "Field": "Primary_Capability",
        "Type": "String",
        "Example": "Personnel Safety",
        "Purpose": "Main operational capability of the team"
    },
    {
        "Field": "Secondary_Capabilities",
        "Type": "List/String",
        "Example": "Incident Control; Access Security",
        "Purpose": "Additional operational capabilities available to the team"
    },
    {
        "Field": "Readiness_Level",
        "Type": "Category",
        "Example": "READY",
        "Purpose": "Current readiness state: READY, LIMITED, or UNAVAILABLE"
    },
    {
        "Field": "Personnel_Strength",
        "Type": "Integer",
        "Example": "6",
        "Purpose": "Synthetic number of personnel currently assigned to the team"
    },
    {
        "Field": "Vehicle_Available",
        "Type": "Boolean",
        "Example": "True",
        "Purpose": "Indicates whether a response vehicle is currently available"
    },
    {
        "Field": "Capability_Tags",
        "Type": "List/String",
        "Example": "Crowd Control; Medical Support",
        "Purpose": "Special equipment or specialist capability tags"
    },
    {
        "Field": "Current_Assignment",
        "Type": "String",
        "Example": "None",
        "Purpose": "Current simulated incident assignment, if any"
    },
    {
        "Field": "Last_Updated",
        "Type": "Datetime",
        "Example": "2026-08-12 17:30:00",
        "Purpose": "Timestamp of the latest simulated team-state update"
    }
]

schema_df = pd.DataFrame(response_team_schema)

print("=" * 90)
print("RESPONSE TEAM REGISTRY — PROPOSED SCHEMA")
print("=" * 90)

display(schema_df)

print("\nSchema Fields :", len(schema_df))
print("\nDesign Principles:")
print("- Team information is entirely synthetic.")
print("- Zones correspond to the fictional Zone A–H dashboard environment.")
print("- Availability and readiness are treated as separate concepts.")
print("- Capabilities will later connect to the existing DSS operational mapping.")
print("- No real military unit, personnel, location, or deployment data is used.")

print("\n" + "=" * 90)
print("SCHEMA DEFINITION COMPLETE")
print("=" * 90)

==========================================================================================
RESPONSE TEAM REGISTRY — PROPOSED SCHEMA
==========================================================================================

,Field,Type,Example,Purpose
0,Team_ID,String,RT-01,Unique identifier for each synthetic response ...
1,Team_Name,String,Response Team 01,Operator-friendly team name
2,Status,Category,AVAILABLE,"Current deployment availability: AVAILABLE, AS..."
3,Current_Zone,Category,Zone B,Current fictional operational zone of the team
4,Primary_Capability,String,Personnel Safety,Main operational capability of the team
5,Secondary_Capabilities,List/String,Incident Control; Access Security,Additional operational capabilities available ...
6,Readiness_Level,Category,READY,"Current readiness state: READY, LIMITED, or UN..."
7,Personnel_Strength,Integer,6,Synthetic number of personnel currently assign...
8,Vehicle_Available,Boolean,True,Indicates whether a response vehicle is curren...
9,Capability_Tags,List/String,Crowd Control; Medical Support,Special equipment or specialist capability tags
10,Current_Assignment,String,None,"Current simulated incident assignment, if any"
11,Last_Updated,Datetime,2026-08-12 17:30:00,Timestamp of the latest simulated team-state u...

Schema Fields : 12

Design Principles:
- Team information is entirely synthetic.
- Zones correspond to the fictional Zone A–H dashboard environment.
- Availability and readiness are treated as separate concepts.
- Capabilities will later connect to the existing DSS operational mapping.
- No real military unit, personnel, location, or deployment data is used.

==========================================================================================
SCHEMA DEFINITION COMPLETE
==========================================================================================

In [3]:
# ======================================================================
# STEP 3 — CONTROLLED RESPONSE CAPABILITY VOCABULARY
# ======================================================================

response_capabilities = [
    {
        "Capability_ID": "CAP-01",
        "Capability_Name": "Personnel Safety",
        "Description": "Response to incidents involving threats, assault, injury risk, or immediate personnel protection."
    },
    {
        "Capability_ID": "CAP-02",
        "Capability_Name": "Incident Control",
        "Description": "Immediate control, stabilization, containment, and coordination of an active incident scene."
    },
    {
        "Capability_ID": "CAP-03",
        "Capability_Name": "Property and Asset Security",
        "Description": "Protection and response involving property, stores, equipment, facilities, or other physical assets."
    },
    {
        "Capability_ID": "CAP-04",
        "Capability_Name": "Access and Perimeter Security",
        "Description": "Control of entry points, restricted areas, perimeter incidents, and unauthorized access."
    },
    {
        "Capability_ID": "CAP-05",
        "Capability_Name": "Investigation Support",
        "Description": "Initial incident investigation support, evidence preservation, documentation, and administrative follow-up."
    },
    {
        "Capability_ID": "CAP-06",
        "Capability_Name": "Controlled Substances Response",
        "Description": "Response capability for narcotics or other controlled-substance related incidents."
    },
    {
        "Capability_ID": "CAP-07",
        "Capability_Name": "Vehicle and Mobility Security",
        "Description": "Response to vehicle-related incidents, mobility disruption, transport security, or vehicle asset protection."
    },
    {
        "Capability_ID": "CAP-08",
        "Capability_Name": "Sensitive Incident Response",
        "Description": "Specialized handling of incidents requiring elevated control, discretion, or restricted-area coordination."
    },
    {
        "Capability_ID": "CAP-09",
        "Capability_Name": "Traffic and Movement Control",
        "Description": "Management of simulated traffic flow, movement restrictions, route control, and incident-area access."
    },
    {
        "Capability_ID": "CAP-10",
        "Capability_Name": "Medical Coordination",
        "Description": "Coordination capability for incidents where medical response or casualty support may be required."
    }
]

capability_df = pd.DataFrame(response_capabilities)

print("=" * 90)
print("CONTROLLED RESPONSE CAPABILITY VOCABULARY")
print("=" * 90)

display(capability_df)

print("\nTotal Defined Capabilities :", len(capability_df))

print("\nDesign Rule:")
print("Operational response categories from the existing DSS will map to one")
print("or more of these controlled capabilities before team matching occurs.")

print("\nExample:")
print("BATTERY")
print("   ↓")
print("Personnel Safety / Provost Response")
print("   ↓")
print("Required Capabilities:")
print("   - Personnel Safety")
print("   - Incident Control")

print("\n" + "=" * 90)
print("CAPABILITY VOCABULARY DEFINITION COMPLETE")
print("=" * 90)

==========================================================================================
CONTROLLED RESPONSE CAPABILITY VOCABULARY
==========================================================================================

,Capability_ID,Capability_Name,Description
0,CAP-01,Personnel Safety,"Response to incidents involving threats, assau..."
1,CAP-02,Incident Control,"Immediate control, stabilization, containment,..."
2,CAP-03,Property and Asset Security,"Protection and response involving property, st..."
3,CAP-04,Access and Perimeter Security,"Control of entry points, restricted areas, per..."
4,CAP-05,Investigation Support,"Initial incident investigation support, eviden..."
5,CAP-06,Controlled Substances Response,Response capability for narcotics or other con...
6,CAP-07,Vehicle and Mobility Security,"Response to vehicle-related incidents, mobilit..."
7,CAP-08,Sensitive Incident Response,Specialized handling of incidents requiring el...
8,CAP-09,Traffic and Movement Control,"Management of simulated traffic flow, movement..."
9,CAP-10,Medical Coordination,Coordination capability for incidents where me...

Total Defined Capabilities : 10

Design Rule:
Operational response categories from the existing DSS will map to one
or more of these controlled capabilities before team matching occurs.

Example:
BATTERY
   ↓
Personnel Safety / Provost Response
   ↓
Required Capabilities:
   - Personnel Safety
   - Incident Control

==========================================================================================
CAPABILITY VOCABULARY DEFINITION COMPLETE
==========================================================================================

In [4]:
# ======================================================================
# STEP 4 — DSS RESPONSE CATEGORY TO REQUIRED CAPABILITY MAPPING
# ======================================================================

response_capability_mapping = [
    {
        "Operational_Response": "Property / Asset Security Response",
        "Primary_Required_Capability": "Property and Asset Security",
        "Secondary_Required_Capabilities": "Incident Control; Access and Perimeter Security"
    },
    {
        "Operational_Response": "Personnel Safety / Provost Response",
        "Primary_Required_Capability": "Personnel Safety",
        "Secondary_Required_Capabilities": "Incident Control; Medical Coordination"
    },
    {
        "Operational_Response": "Administrative / Investigation Response",
        "Primary_Required_Capability": "Investigation Support",
        "Secondary_Required_Capabilities": "Incident Control"
    },
    {
        "Operational_Response": "Controlled Substances / Security Response",
        "Primary_Required_Capability": "Controlled Substances Response",
        "Secondary_Required_Capabilities": "Incident Control; Investigation Support"
    },
    {
        "Operational_Response": "Vehicle / Mobility Security Response",
        "Primary_Required_Capability": "Vehicle and Mobility Security",
        "Secondary_Required_Capabilities": "Traffic and Movement Control; Incident Control"
    },
    {
        "Operational_Response": "Sensitive Incident / Specialized Response",
        "Primary_Required_Capability": "Sensitive Incident Response",
        "Secondary_Required_Capabilities": "Access and Perimeter Security; Incident Control"
    }
]

response_capability_df = pd.DataFrame(response_capability_mapping)

print("=" * 100)
print("DSS RESPONSE CATEGORY → REQUIRED CAPABILITY MAPPING")
print("=" * 100)

display(response_capability_df)

# ----------------------------------------------------------------------
# Validation against controlled capability vocabulary
# ----------------------------------------------------------------------

valid_capabilities = set(capability_df["Capability_Name"])

validation_issues = []

for _, row in response_capability_df.iterrows():

    primary = row["Primary_Required_Capability"]

    secondary = [
        cap.strip()
        for cap in row["Secondary_Required_Capabilities"].split(";")
    ]

    if primary not in valid_capabilities:
        validation_issues.append(
            f"Invalid primary capability: {primary}"
        )

    for capability in secondary:
        if capability not in valid_capabilities:
            validation_issues.append(
                f"Invalid secondary capability: {capability}"
            )

print("\nValidation Results:")

if not validation_issues:
    print("✓ All mapped capabilities exist in the controlled vocabulary.")
else:
    for issue in validation_issues:
        print("✗", issue)

print("\nOperational Flow Example:")
print("BATTERY")
print("   ↓")
print("Existing DSS")
print("   ↓")
print("Personnel Safety / Provost Response")
print("   ↓")
print("Primary Capability   : Personnel Safety")
print("Secondary Capability : Incident Control")
print("Secondary Capability : Medical Coordination")
print("   ↓")
print("Response Team Registry")
print("   ↓")
print("Eligible teams evaluated dynamically")

print("\n" + "=" * 100)
print("RESPONSE CAPABILITY MAPPING COMPLETE")
print("=" * 100)

====================================================================================================
DSS RESPONSE CATEGORY → REQUIRED CAPABILITY MAPPING
====================================================================================================

,Operational_Response,Primary_Required_Capability,Secondary_Required_Capabilities
0,Property / Asset Security Response,Property and Asset Security,Incident Control; Access and Perimeter Security
1,Personnel Safety / Provost Response,Personnel Safety,Incident Control; Medical Coordination
2,Administrative / Investigation Response,Investigation Support,Incident Control
3,Controlled Substances / Security Response,Controlled Substances Response,Incident Control; Investigation Support
4,Vehicle / Mobility Security Response,Vehicle and Mobility Security,Traffic and Movement Control; Incident Control
5,Sensitive Incident / Specialized Response,Sensitive Incident Response,Access and Perimeter Security; Incident Control

Validation Results:
✓ All mapped capabilities exist in the controlled vocabulary.

Operational Flow Example:
BATTERY
   ↓
Existing DSS
   ↓
Personnel Safety / Provost Response
   ↓
Primary Capability   : Personnel Safety
Secondary Capability : Incident Control
Secondary Capability : Medical Coordination
   ↓
Response Team Registry
   ↓
Eligible teams evaluated dynamically

====================================================================================================
RESPONSE CAPABILITY MAPPING COMPLETE
====================================================================================================

In [5]:
# ======================================================================
# STEP 5 — GENERATE SYNTHETIC RESPONSE TEAM REGISTRY
# ======================================================================

from datetime import datetime

response_team_records = [
    {
        "Team_ID": "RT-01",
        "Team_Name": "Response Team 01",
        "Status": "AVAILABLE",
        "Current_Zone": "Zone A",
        "Primary_Capability": "Access and Perimeter Security",
        "Secondary_Capabilities": "Incident Control; Personnel Safety",
        "Readiness_Level": "READY",
        "Personnel_Strength": 6,
        "Vehicle_Available": True,
        "Capability_Tags": "Entry Control; Restricted Area Support",
        "Current_Assignment": "None",
        "Last_Updated": datetime.now()
    },
    {
        "Team_ID": "RT-02",
        "Team_Name": "Response Team 02",
        "Status": "AVAILABLE",
        "Current_Zone": "Zone B",
        "Primary_Capability": "Personnel Safety",
        "Secondary_Capabilities": "Incident Control; Medical Coordination",
        "Readiness_Level": "READY",
        "Personnel_Strength": 7,
        "Vehicle_Available": True,
        "Capability_Tags": "Personnel Protection; Immediate Response",
        "Current_Assignment": "None",
        "Last_Updated": datetime.now()
    },
    {
        "Team_ID": "RT-03",
        "Team_Name": "Response Team 03",
        "Status": "OFFLINE",
        "Current_Zone": "Zone C",
        "Primary_Capability": "Vehicle and Mobility Security",
        "Secondary_Capabilities": "Traffic and Movement Control; Incident Control",
        "Readiness_Level": "UNAVAILABLE",
        "Personnel_Strength": 5,
        "Vehicle_Available": False,
        "Capability_Tags": "Vehicle Security; Route Control",
        "Current_Assignment": "None",
        "Last_Updated": datetime.now()
    },
    {
        "Team_ID": "RT-04",
        "Team_Name": "Response Team 04",
        "Status": "AVAILABLE",
        "Current_Zone": "Zone D",
        "Primary_Capability": "Property and Asset Security",
        "Secondary_Capabilities": "Incident Control; Access and Perimeter Security",
        "Readiness_Level": "READY",
        "Personnel_Strength": 6,
        "Vehicle_Available": True,
        "Capability_Tags": "Stores Security; Asset Protection",
        "Current_Assignment": "None",
        "Last_Updated": datetime.now()
    },
    {
        "Team_ID": "RT-05",
        "Team_Name": "Response Team 05",
        "Status": "AVAILABLE",
        "Current_Zone": "Zone E",
        "Primary_Capability": "Personnel Safety",
        "Secondary_Capabilities": "Incident Control; Investigation Support",
        "Readiness_Level": "LIMITED",
        "Personnel_Strength": 5,
        "Vehicle_Available": True,
        "Capability_Tags": "Personnel Protection; Investigation Support",
        "Current_Assignment": "None",
        "Last_Updated": datetime.now()
    },
    {
        "Team_ID": "RT-06",
        "Team_Name": "Response Team 06",
        "Status": "ASSIGNED",
        "Current_Zone": "Zone F",
        "Primary_Capability": "Controlled Substances Response",
        "Secondary_Capabilities": "Incident Control; Investigation Support",
        "Readiness_Level": "READY",
        "Personnel_Strength": 6,
        "Vehicle_Available": True,
        "Capability_Tags": "Controlled Substance Handling; Evidence Support",
        "Current_Assignment": "SIM-INC-0042",
        "Last_Updated": datetime.now()
    },
    {
        "Team_ID": "RT-07",
        "Team_Name": "Response Team 07",
        "Status": "AVAILABLE",
        "Current_Zone": "Zone G",
        "Primary_Capability": "Investigation Support",
        "Secondary_Capabilities": "Incident Control; Property and Asset Security",
        "Readiness_Level": "READY",
        "Personnel_Strength": 4,
        "Vehicle_Available": True,
        "Capability_Tags": "Evidence Preservation; Documentation",
        "Current_Assignment": "None",
        "Last_Updated": datetime.now()
    },
    {
        "Team_ID": "RT-08",
        "Team_Name": "Response Team 08",
        "Status": "AVAILABLE",
        "Current_Zone": "Zone H",
        "Primary_Capability": "Sensitive Incident Response",
        "Secondary_Capabilities": "Access and Perimeter Security; Incident Control",
        "Readiness_Level": "READY",
        "Personnel_Strength": 6,
        "Vehicle_Available": True,
        "Capability_Tags": "Restricted Area Support; Sensitive Incident Handling",
        "Current_Assignment": "None",
        "Last_Updated": datetime.now()
    },
    {
        "Team_ID": "RT-09",
        "Team_Name": "Response Team 09",
        "Status": "AVAILABLE",
        "Current_Zone": "Zone C",
        "Primary_Capability": "Vehicle and Mobility Security",
        "Secondary_Capabilities": "Traffic and Movement Control; Incident Control",
        "Readiness_Level": "READY",
        "Personnel_Strength": 6,
        "Vehicle_Available": True,
        "Capability_Tags": "Vehicle Security; Traffic Control",
        "Current_Assignment": "None",
        "Last_Updated": datetime.now()
    },
    {
        "Team_ID": "RT-10",
        "Team_Name": "Response Team 10",
        "Status": "AVAILABLE",
        "Current_Zone": "Zone A",
        "Primary_Capability": "Controlled Substances Response",
        "Secondary_Capabilities": "Investigation Support; Incident Control",
        "Readiness_Level": "LIMITED",
        "Personnel_Strength": 5,
        "Vehicle_Available": False,
        "Capability_Tags": "Evidence Support; Controlled Substance Response",
        "Current_Assignment": "None",
        "Last_Updated": datetime.now()
    }
]

response_team_df = pd.DataFrame(response_team_records)

# ----------------------------------------------------------------------
# Basic Registry Validation
# ----------------------------------------------------------------------

expected_columns = [item["Field"] for item in response_team_schema]

missing_columns = [
    col for col in expected_columns
    if col not in response_team_df.columns
]

duplicate_team_ids = response_team_df["Team_ID"].duplicated().sum()

invalid_status = response_team_df[
    ~response_team_df["Status"].isin(["AVAILABLE", "ASSIGNED", "OFFLINE"])
]

invalid_readiness = response_team_df[
    ~response_team_df["Readiness_Level"].isin(
        ["READY", "LIMITED", "UNAVAILABLE"]
    )
]

valid_zones = [f"Zone {letter}" for letter in "ABCDEFGH"]

invalid_zones = response_team_df[
    ~response_team_df["Current_Zone"].isin(valid_zones)
]

# ----------------------------------------------------------------------
# Display
# ----------------------------------------------------------------------

print("=" * 110)
print("SYNTHETIC RESPONSE TEAM REGISTRY")
print("=" * 110)

display(response_team_df)

print("\nRegistry Summary")
print("-" * 50)
print("Total Teams       :", len(response_team_df))
print("Available Teams   :", (response_team_df["Status"] == "AVAILABLE").sum())
print("Assigned Teams    :", (response_team_df["Status"] == "ASSIGNED").sum())
print("Offline Teams     :", (response_team_df["Status"] == "OFFLINE").sum())

print("\nValidation")
print("-" * 50)
print("Missing Columns    :", len(missing_columns))
print("Duplicate Team IDs :", duplicate_team_ids)
print("Invalid Statuses   :", len(invalid_status))
print("Invalid Readiness  :", len(invalid_readiness))
print("Invalid Zones      :", len(invalid_zones))

if (
    len(missing_columns) == 0
    and duplicate_team_ids == 0
    and len(invalid_status) == 0
    and len(invalid_readiness) == 0
    and len(invalid_zones) == 0
):
    print("\n✓ Response Team Registry validation PASSED.")
else:
    print("\n✗ Response Team Registry validation FAILED.")

print("\n" + "=" * 110)
print("SYNTHETIC RESPONSE TEAM REGISTRY GENERATION COMPLETE")
print("=" * 110)

==============================================================================================================
SYNTHETIC RESPONSE TEAM REGISTRY
==============================================================================================================

,Team_ID,Team_Name,Status,Current_Zone,Primary_Capability,Secondary_Capabilities,Readiness_Level,Personnel_Strength,Vehicle_Available,Capability_Tags,Current_Assignment,Last_Updated
0,RT-01,Response Team 01,AVAILABLE,Zone A,Access and Perimeter Security,Incident Control; Personnel Safety,READY,6,True,Entry Control; Restricted Area Support,None,2026-08-13 09:08:10.287188
1,RT-02,Response Team 02,AVAILABLE,Zone B,Personnel Safety,Incident Control; Medical Coordination,READY,7,True,Personnel Protection; Immediate Response,None,2026-08-13 09:08:10.287194
2,RT-03,Response Team 03,OFFLINE,Zone C,Vehicle and Mobility Security,Traffic and Movement Control; Incident Control,UNAVAILABLE,5,False,Vehicle Security; Route Control,None,2026-08-13 09:08:10.287195
3,RT-04,Response Team 04,AVAILABLE,Zone D,Property and Asset Security,Incident Control; Access and Perimeter Security,READY,6,True,Stores Security; Asset Protection,None,2026-08-13 09:08:10.287205
4,RT-05,Response Team 05,AVAILABLE,Zone E,Personnel Safety,Incident Control; Investigation Support,LIMITED,5,True,Personnel Protection; Investigation Support,None,2026-08-13 09:08:10.287205
5,RT-06,Response Team 06,ASSIGNED,Zone F,Controlled Substances Response,Incident Control; Investigation Support,READY,6,True,Controlled Substance Handling; Evidence Support,SIM-INC-0042,2026-08-13 09:08:10.287206
6,RT-07,Response Team 07,AVAILABLE,Zone G,Investigation Support,Incident Control; Property and Asset Security,READY,4,True,Evidence Preservation; Documentation,None,2026-08-13 09:08:10.287207
7,RT-08,Response Team 08,AVAILABLE,Zone H,Sensitive Incident Response,Access and Perimeter Security; Incident Control,READY,6,True,Restricted Area Support; Sensitive Incident Ha...,None,2026-08-13 09:08:10.287208
8,RT-09,Response Team 09,AVAILABLE,Zone C,Vehicle and Mobility Security,Traffic and Movement Control; Incident Control,READY,6,True,Vehicle Security; Traffic Control,None,2026-08-13 09:08:10.287209
9,RT-10,Response Team 10,AVAILABLE,Zone A,Controlled Substances Response,Investigation Support; Incident Control,LIMITED,5,False,Evidence Support; Controlled Substance Response,None,2026-08-13 09:08:10.287210

Registry Summary
--------------------------------------------------
Total Teams       : 10
Available Teams   : 8
Assigned Teams    : 1
Offline Teams     : 1

Validation
--------------------------------------------------
Missing Columns    : 0
Duplicate Team IDs : 0
Invalid Statuses   : 0
Invalid Readiness  : 0
Invalid Zones      : 0

✓ Response Team Registry validation PASSED.

==============================================================================================================
SYNTHETIC RESPONSE TEAM REGISTRY GENERATION COMPLETE
==============================================================================================================

In [6]:
# ======================================================================
# STEP 6 — RESPONSE TEAM CAPABILITY COVERAGE VALIDATION
# ======================================================================

# ----------------------------------------------------------------------
# Collect all capabilities possessed by each team
# ----------------------------------------------------------------------

def extract_team_capabilities(row):
    """
    Combine primary and secondary capabilities for one response team.
    """

    capabilities = {row["Primary_Capability"]}

    secondary = [
        cap.strip()
        for cap in str(row["Secondary_Capabilities"]).split(";")
        if cap.strip()
    ]

    capabilities.update(secondary)

    return capabilities


response_team_df["All_Capabilities"] = response_team_df.apply(
    extract_team_capabilities,
    axis=1
)

# ----------------------------------------------------------------------
# Required PRIMARY capabilities coming from the existing DSS mapping
# ----------------------------------------------------------------------

required_primary_capabilities = set(
    response_capability_df["Primary_Required_Capability"]
)

# Capabilities represented somewhere in the team registry
registry_capabilities = set()

for capabilities in response_team_df["All_Capabilities"]:
    registry_capabilities.update(capabilities)

missing_required_capabilities = (
    required_primary_capabilities - registry_capabilities
)

# ----------------------------------------------------------------------
# Coverage Report
# ----------------------------------------------------------------------

coverage_records = []

for capability in sorted(required_primary_capabilities):

    matching_teams = response_team_df[
        response_team_df["All_Capabilities"].apply(
            lambda x: capability in x
        )
    ]

    available_matching_teams = matching_teams[
        (matching_teams["Status"] == "AVAILABLE")
        &
        (matching_teams["Readiness_Level"] != "UNAVAILABLE")
    ]

    coverage_records.append(
        {
            "Required_Capability": capability,
            "Total_Capable_Teams": len(matching_teams),
            "Currently_Deployable_Teams": len(available_matching_teams),
            "Capable_Team_IDs": ", ".join(
                matching_teams["Team_ID"].tolist()
            ),
            "Deployable_Team_IDs": ", ".join(
                available_matching_teams["Team_ID"].tolist()
            )
        }
    )

capability_coverage_df = pd.DataFrame(coverage_records)

print("=" * 110)
print("RESPONSE TEAM CAPABILITY COVERAGE VALIDATION")
print("=" * 110)

display(capability_coverage_df)

print("\nCoverage Summary")
print("-" * 60)

print(
    "DSS Primary Capabilities Required :",
    len(required_primary_capabilities)
)

print(
    "Capabilities Present in Registry  :",
    len(required_primary_capabilities - missing_required_capabilities)
)

print(
    "Missing Required Capabilities     :",
    len(missing_required_capabilities)
)

if len(missing_required_capabilities) == 0:
    print("\n✓ Every primary DSS-required capability is represented in the registry.")
else:
    print("\n✗ Missing capabilities:")
    for capability in sorted(missing_required_capabilities):
        print("  -", capability)

# ----------------------------------------------------------------------
# Current Deployability Check
# ----------------------------------------------------------------------

no_deployable_team = capability_coverage_df[
    capability_coverage_df["Currently_Deployable_Teams"] == 0
]

if len(no_deployable_team) == 0:
    print(
        "✓ Every primary capability currently has at least one "
        "deployable response team."
    )
else:
    print(
        "⚠ Some capabilities currently have no immediately "
        "deployable response team:"
    )

    display(
        no_deployable_team[
            [
                "Required_Capability",
                "Capable_Team_IDs"
            ]
        ]
    )

print("\n" + "=" * 110)
print("CAPABILITY COVERAGE VALIDATION COMPLETE")
print("=" * 110)

==============================================================================================================
RESPONSE TEAM CAPABILITY COVERAGE VALIDATION
==============================================================================================================

,Required_Capability,Total_Capable_Teams,Currently_Deployable_Teams,Capable_Team_IDs,Deployable_Team_IDs
0,Controlled Substances Response,2,1,"RT-06, RT-10",RT-10
1,Investigation Support,4,3,"RT-05, RT-06, RT-07, RT-10","RT-05, RT-07, RT-10"
2,Personnel Safety,3,3,"RT-01, RT-02, RT-05","RT-01, RT-02, RT-05"
3,Property and Asset Security,2,2,"RT-04, RT-07","RT-04, RT-07"
4,Sensitive Incident Response,1,1,RT-08,RT-08
5,Vehicle and Mobility Security,2,1,"RT-03, RT-09",RT-09

Coverage Summary
------------------------------------------------------------
DSS Primary Capabilities Required : 6
Capabilities Present in Registry  : 6
Missing Required Capabilities     : 0

✓ Every primary DSS-required capability is represented in the registry.
✓ Every primary capability currently has at least one deployable response team.

==============================================================================================================
CAPABILITY COVERAGE VALIDATION COMPLETE
==============================================================================================================

In [7]:
# ======================================================================
# STEP 7 — SAVE VALIDATED RESPONSE TEAM REGISTRY
# ======================================================================

# Remove helper column before saving
registry_to_save = response_team_df.drop(
    columns=["All_Capabilities"],
    errors="ignore"
).copy()

# Save baseline synthetic registry
registry_to_save.to_csv(
    RESPONSE_TEAM_REGISTRY_PATH,
    index=False
)

print("=" * 80)
print("SAVING RESPONSE TEAM REGISTRY")
print("=" * 80)

print("\nSaved To:")
print(RESPONSE_TEAM_REGISTRY_PATH)

print("\nSaved Shape:")
print(registry_to_save.shape)

print("\nSaved Columns:")
for column in registry_to_save.columns:
    print(" -", column)

# Verify file creation
if RESPONSE_TEAM_REGISTRY_PATH.exists():
    print("\n✓ Response Team Registry saved successfully.")
else:
    print("\n✗ Registry file was not created.")

print("\nIMPORTANT:")
print("This file represents the BASELINE SYNTHETIC resource state.")
print("Future assignment logic may modify team status dynamically,")
print("but this validated registry provides the initial resource configuration.")

print("\n" + "=" * 80)
print("RESPONSE TEAM REGISTRY SAVE COMPLETE")
print("=" * 80)

================================================================================
SAVING RESPONSE TEAM REGISTRY
================================================================================

Saved To:
/content/drive/MyDrive/Army_Provost_ML_Project/Outputs/Response_Team_Registry.csv

Saved Shape:
(10, 12)

Saved Columns:
 - Team_ID
 - Team_Name
 - Status
 - Current_Zone
 - Primary_Capability
 - Secondary_Capabilities
 - Readiness_Level
 - Personnel_Strength
 - Vehicle_Available
 - Capability_Tags
 - Current_Assignment
 - Last_Updated

✓ Response Team Registry saved successfully.

IMPORTANT:
This file represents the BASELINE SYNTHETIC resource state.
Future assignment logic may modify team status dynamically,
but this validated registry provides the initial resource configuration.

================================================================================
RESPONSE TEAM REGISTRY SAVE COMPLETE
================================================================================

In [8]:
# ======================================================================
# STEP 8 — RESOURCE ALLOCATION DECISION FACTORS
# ======================================================================

allocation_factor_design = [
    {
        "Factor": "Team Availability",
        "Role": "ELIGIBILITY GATE",
        "Rule": "Status must be AVAILABLE",
        "Reason": "ASSIGNED or OFFLINE teams must not be treated as immediately deployable."
    },
    {
        "Factor": "Operational Readiness",
        "Role": "ELIGIBILITY + RANKING",
        "Rule": "UNAVAILABLE is excluded; READY ranks above LIMITED",
        "Reason": "Readiness affects whether a team can respond effectively at the current time."
    },
    {
        "Factor": "Required Capability Match",
        "Role": "ELIGIBILITY GATE",
        "Rule": "Team must possess the required primary capability",
        "Reason": "A team lacking the core required capability should not be recommended."
    },
    {
        "Factor": "Capability Priority",
        "Role": "RANKING",
        "Rule": "Primary capability match ranks above secondary capability match",
        "Reason": "Teams specialized in the required capability should generally be preferred."
    },
    {
        "Factor": "Zone Relationship",
        "Role": "RANKING",
        "Rule": "Same fictional zone ranks above a different zone",
        "Reason": "For the prototype, zone proximity represents likely response convenience without using real coordinates."
    },
    {
        "Factor": "Vehicle Availability",
        "Role": "RANKING",
        "Rule": "Vehicle availability may improve suitability",
        "Reason": "Mobility can influence operational responsiveness, especially across zones."
    },
    {
        "Factor": "Personnel Strength",
        "Role": "SECONDARY RANKING",
        "Rule": "Higher available personnel strength may provide a small ranking advantage",
        "Reason": "Personnel strength is useful context but should not overpower capability or readiness."
    }
]

allocation_factor_df = pd.DataFrame(allocation_factor_design)

print("=" * 110)
print("RESOURCE ALLOCATION DECISION FACTOR DESIGN")
print("=" * 110)

display(allocation_factor_df)

print("\nDecision Architecture")
print("-" * 60)

print("STAGE 1 — ELIGIBILITY")
print("1. Team must be AVAILABLE")
print("2. Team must not be UNAVAILABLE")
print("3. Team must possess the required primary capability")

print("\nSTAGE 2 — RANKING")
print("1. Primary vs secondary capability match")
print("2. READY vs LIMITED readiness")
print("3. Same-zone vs different-zone position")
print("4. Vehicle availability")
print("5. Personnel strength")

print("\nImportant Principle:")
print("A ranking score is calculated ONLY after a team passes")
print("the minimum deployment eligibility conditions.")

print("\n" + "=" * 110)
print("RESOURCE ALLOCATION FACTOR DESIGN COMPLETE")
print("=" * 110)

==============================================================================================================
RESOURCE ALLOCATION DECISION FACTOR DESIGN
==============================================================================================================

,Factor,Role,Rule,Reason
0,Team Availability,ELIGIBILITY GATE,Status must be AVAILABLE,ASSIGNED or OFFLINE teams must not be treated ...
1,Operational Readiness,ELIGIBILITY + RANKING,UNAVAILABLE is excluded; READY ranks above LIM...,Readiness affects whether a team can respond e...
2,Required Capability Match,ELIGIBILITY GATE,Team must possess the required primary capability,A team lacking the core required capability sh...
3,Capability Priority,RANKING,Primary capability match ranks above secondary...,Teams specialized in the required capability s...
4,Zone Relationship,RANKING,Same fictional zone ranks above a different zone,"For the prototype, zone proximity represents l..."
5,Vehicle Availability,RANKING,Vehicle availability may improve suitability,Mobility can influence operational responsiven...
6,Personnel Strength,SECONDARY RANKING,Higher available personnel strength may provid...,Personnel strength is useful context but shoul...

Decision Architecture
------------------------------------------------------------
STAGE 1 — ELIGIBILITY
1. Team must be AVAILABLE
2. Team must not be UNAVAILABLE
3. Team must possess the required primary capability

STAGE 2 — RANKING
1. Primary vs secondary capability match
2. READY vs LIMITED readiness
3. Same-zone vs different-zone position
4. Vehicle availability
5. Personnel strength

Important Principle:
A ranking score is calculated ONLY after a team passes
the minimum deployment eligibility conditions.

==============================================================================================================
RESOURCE ALLOCATION FACTOR DESIGN COMPLETE
==============================================================================================================

In [9]:
# ======================================================================
# STEP 9 — TEAM SUITABILITY SCORING METHODOLOGY
# ======================================================================

scoring_methodology = [
    {
        "Factor": "Capability Match",
        "Condition": "Required capability is team's PRIMARY capability",
        "Points": 40,
        "Justification": "Primary specialization is the strongest indicator of operational suitability."
    },
    {
        "Factor": "Capability Match",
        "Condition": "Required capability is team's SECONDARY capability",
        "Points": 30,
        "Justification": "Secondary capability is valid but ranks below primary specialization."
    },
    {
        "Factor": "Readiness",
        "Condition": "READY",
        "Points": 25,
        "Justification": "Fully ready teams should be preferred over teams operating with limitations."
    },
    {
        "Factor": "Readiness",
        "Condition": "LIMITED",
        "Points": 12,
        "Justification": "Limited teams remain deployable but receive a meaningful ranking penalty."
    },
    {
        "Factor": "Zone Relationship",
        "Condition": "Same fictional zone as incident",
        "Points": 20,
        "Justification": "Same-zone positioning is used as a simple proxy for response convenience."
    },
    {
        "Factor": "Zone Relationship",
        "Condition": "Different fictional zone",
        "Points": 10,
        "Justification": "Different-zone teams remain usable but receive a smaller location score."
    },
    {
        "Factor": "Vehicle Availability",
        "Condition": "Vehicle available",
        "Points": 10,
        "Justification": "Mobility can improve response capability, particularly for cross-zone deployment."
    },
    {
        "Factor": "Personnel Strength",
        "Condition": "Scaled contribution",
        "Points": 5,
        "Justification": "Personnel strength is useful supporting context but must not dominate operational capability."
    }
]

scoring_methodology_df = pd.DataFrame(scoring_methodology)

print("=" * 110)
print("TEAM SUITABILITY SCORING METHODOLOGY")
print("=" * 110)

display(scoring_methodology_df)

print("\nSCORING ARCHITECTURE")
print("-" * 60)

print("Eligibility Gates:")
print("  ✓ Status must be AVAILABLE")
print("  ✓ Readiness must not be UNAVAILABLE")
print("  ✓ Required primary capability must be possessed by the team")

print("\nMaximum Ranking Components:")
print("  Capability Match     : 40 points")
print("  Readiness            : 25 points")
print("  Zone Relationship    : 20 points")
print("  Vehicle Availability : 10 points")
print("  Personnel Strength   :  5 points")
print("                         ----------")
print("  Maximum Score        : 100 points")

print("\nCapability Rule:")
print("  Primary match   = 40")
print("  Secondary match = 30")

print("\nPersonnel Strength Rule:")
print("  7+ personnel = 5 points")
print("  6 personnel  = 4 points")
print("  5 personnel  = 3 points")
print("  4 personnel  = 2 points")
print("  <4 personnel = 1 point")

print("\nInterpretation:")
print("The score ranks teams that have ALREADY passed deployment eligibility.")
print("It does not grant deployment authority.")
print("The final selection remains subject to human operator confirmation.")

print("\n" + "=" * 110)
print("TEAM SUITABILITY SCORING METHODOLOGY COMPLETE")
print("=" * 110)

==============================================================================================================
TEAM SUITABILITY SCORING METHODOLOGY
==============================================================================================================

,Factor,Condition,Points,Justification
0,Capability Match,Required capability is team's PRIMARY capability,40,Primary specialization is the strongest indica...
1,Capability Match,Required capability is team's SECONDARY capabi...,30,Secondary capability is valid but ranks below ...
2,Readiness,READY,25,Fully ready teams should be preferred over tea...
3,Readiness,LIMITED,12,Limited teams remain deployable but receive a ...
4,Zone Relationship,Same fictional zone as incident,20,Same-zone positioning is used as a simple prox...
5,Zone Relationship,Different fictional zone,10,Different-zone teams remain usable but receive...
6,Vehicle Availability,Vehicle available,10,"Mobility can improve response capability, part..."
7,Personnel Strength,Scaled contribution,5,Personnel strength is useful supporting contex...

SCORING ARCHITECTURE
------------------------------------------------------------
Eligibility Gates:
  ✓ Status must be AVAILABLE
  ✓ Readiness must not be UNAVAILABLE
  ✓ Required primary capability must be possessed by the team

Maximum Ranking Components:
  Capability Match     : 40 points
  Readiness            : 25 points
  Zone Relationship    : 20 points
  Vehicle Availability : 10 points
  Personnel Strength   :  5 points
                         ----------
  Maximum Score        : 100 points

Capability Rule:
  Primary match   = 40
  Secondary match = 30

Personnel Strength Rule:
  7+ personnel = 5 points
  6 personnel  = 4 points
  5 personnel  = 3 points
  4 personnel  = 2 points
  <4 personnel = 1 point

Interpretation:
The score ranks teams that have ALREADY passed deployment eligibility.
It does not grant deployment authority.
The final selection remains subject to human operator confirmation.

==============================================================================================================
TEAM SUITABILITY SCORING METHODOLOGY COMPLETE
==============================================================================================================

In [10]:
# ======================================================================
# STEP 10 — ELIGIBLE RESPONSE TEAM FILTER
# ======================================================================

def get_team_capabilities(row):
    """
    Return the complete capability set for a response team.
    """

    capabilities = {row["Primary_Capability"]}

    secondary = [
        cap.strip()
        for cap in str(row["Secondary_Capabilities"]).split(";")
        if cap.strip()
    ]

    capabilities.update(secondary)

    return capabilities


def filter_eligible_response_teams(
    team_registry,
    required_capability
):
    """
    Filter teams that are immediately eligible for deployment.

    Eligibility Rules:
    1. Status must be AVAILABLE
    2. Readiness must not be UNAVAILABLE
    3. Team must possess the required capability
       either as a primary or secondary capability
    """

    eligible_records = []

    for _, team in team_registry.iterrows():

        team_capabilities = get_team_capabilities(team)

        is_available = (
            team["Status"] == "AVAILABLE"
        )

        is_ready_enough = (
            team["Readiness_Level"] != "UNAVAILABLE"
        )

        has_required_capability = (
            required_capability in team_capabilities
        )

        if (
            is_available
            and is_ready_enough
            and has_required_capability
        ):
            eligible_records.append(team)

    if eligible_records:
        eligible_df = pd.DataFrame(eligible_records).reset_index(drop=True)
    else:
        eligible_df = pd.DataFrame(columns=team_registry.columns)

    return eligible_df


# ----------------------------------------------------------------------
# TEST CASE — PERSONNEL SAFETY
# ----------------------------------------------------------------------

test_required_capability = "Personnel Safety"

eligible_test_df = filter_eligible_response_teams(
    response_team_df,
    test_required_capability
)

print("=" * 100)
print("ELIGIBLE RESPONSE TEAM FILTER — TEST")
print("=" * 100)

print("\nRequired Capability:")
print(test_required_capability)

print("\nEligible Teams:")
display(
    eligible_test_df[
        [
            "Team_ID",
            "Team_Name",
            "Status",
            "Current_Zone",
            "Primary_Capability",
            "Secondary_Capabilities",
            "Readiness_Level",
            "Personnel_Strength",
            "Vehicle_Available"
        ]
    ]
)

print("\nEligible Team Count:", len(eligible_test_df))

print("\nExpected Logic:")
print("- RT-01 should qualify through SECONDARY Personnel Safety capability.")
print("- RT-02 should qualify through PRIMARY Personnel Safety capability.")
print("- RT-05 should qualify through PRIMARY Personnel Safety capability.")
print("- ASSIGNED / OFFLINE teams must not appear.")

print("\n" + "=" * 100)
print("ELIGIBILITY FILTER TEST COMPLETE")
print("=" * 100)

====================================================================================================
ELIGIBLE RESPONSE TEAM FILTER — TEST
====================================================================================================

Required Capability:
Personnel Safety

Eligible Teams:

,Team_ID,Team_Name,Status,Current_Zone,Primary_Capability,Secondary_Capabilities,Readiness_Level,Personnel_Strength,Vehicle_Available
0,RT-01,Response Team 01,AVAILABLE,Zone A,Access and Perimeter Security,Incident Control; Personnel Safety,READY,6,True
1,RT-02,Response Team 02,AVAILABLE,Zone B,Personnel Safety,Incident Control; Medical Coordination,READY,7,True
2,RT-05,Response Team 05,AVAILABLE,Zone E,Personnel Safety,Incident Control; Investigation Support,LIMITED,5,True

Eligible Team Count: 3

Expected Logic:
- RT-01 should qualify through SECONDARY Personnel Safety capability.
- RT-02 should qualify through PRIMARY Personnel Safety capability.
- RT-05 should qualify through PRIMARY Personnel Safety capability.
- ASSIGNED / OFFLINE teams must not appear.

====================================================================================================
ELIGIBILITY FILTER TEST COMPLETE
====================================================================================================

In [11]:
# ======================================================================
# STEP 11 — TEAM SUITABILITY SCORING FUNCTION
# ======================================================================

def personnel_strength_score(strength):
    """
    Convert personnel strength into a small supporting score.
    """
    if strength >= 7:
        return 5
    elif strength == 6:
        return 4
    elif strength == 5:
        return 3
    elif strength == 4:
        return 2
    else:
        return 1


def score_response_team(
    team,
    required_capability,
    incident_zone
):
    """
    Calculate suitability score for an already eligible response team.

    Maximum score = 100
    """

    score = 0
    score_breakdown = {}

    # --------------------------------------------------------------
    # 1. Capability Match
    # --------------------------------------------------------------

    if team["Primary_Capability"] == required_capability:
        capability_score = 40
        capability_match_type = "PRIMARY"

    else:
        capability_score = 30
        capability_match_type = "SECONDARY"

    score += capability_score
    score_breakdown["Capability_Score"] = capability_score

    # --------------------------------------------------------------
    # 2. Readiness
    # --------------------------------------------------------------

    if team["Readiness_Level"] == "READY":
        readiness_score = 25

    elif team["Readiness_Level"] == "LIMITED":
        readiness_score = 12

    else:
        readiness_score = 0

    score += readiness_score
    score_breakdown["Readiness_Score"] = readiness_score

    # --------------------------------------------------------------
    # 3. Zone Relationship
    # --------------------------------------------------------------

    if team["Current_Zone"] == incident_zone:
        zone_score = 20
        zone_match = "SAME ZONE"

    else:
        zone_score = 10
        zone_match = "DIFFERENT ZONE"

    score += zone_score
    score_breakdown["Zone_Score"] = zone_score

    # --------------------------------------------------------------
    # 4. Vehicle Availability
    # --------------------------------------------------------------

    vehicle_score = 10 if team["Vehicle_Available"] else 0

    score += vehicle_score
    score_breakdown["Vehicle_Score"] = vehicle_score

    # --------------------------------------------------------------
    # 5. Personnel Strength
    # --------------------------------------------------------------

    strength_score = personnel_strength_score(
        team["Personnel_Strength"]
    )

    score += strength_score
    score_breakdown["Personnel_Score"] = strength_score

    # --------------------------------------------------------------
    # Return result
    # --------------------------------------------------------------

    return {
        "Team_ID": team["Team_ID"],
        "Team_Name": team["Team_Name"],
        "Current_Zone": team["Current_Zone"],
        "Capability_Match": capability_match_type,
        "Readiness_Level": team["Readiness_Level"],
        "Zone_Relationship": zone_match,
        "Vehicle_Available": team["Vehicle_Available"],
        "Personnel_Strength": team["Personnel_Strength"],
        **score_breakdown,
        "Suitability_Score": score
    }


def rank_eligible_response_teams(
    eligible_teams,
    required_capability,
    incident_zone
):
    """
    Score and rank all eligible response teams.
    """

    ranking_records = []

    for _, team in eligible_teams.iterrows():

        result = score_response_team(
            team,
            required_capability,
            incident_zone
        )

        ranking_records.append(result)

    ranking_df = pd.DataFrame(ranking_records)

    if not ranking_df.empty:

        ranking_df = ranking_df.sort_values(
            by="Suitability_Score",
            ascending=False
        ).reset_index(drop=True)

        ranking_df.insert(
            0,
            "Rank",
            range(1, len(ranking_df) + 1)
        )

    return ranking_df


# ======================================================================
# TEST CASE
# ======================================================================

test_required_capability = "Personnel Safety"
test_incident_zone = "Zone B"

eligible_test_df = filter_eligible_response_teams(
    response_team_df,
    test_required_capability
)

ranking_test_df = rank_eligible_response_teams(
    eligible_test_df,
    test_required_capability,
    test_incident_zone
)

print("=" * 110)
print("RESPONSE TEAM SUITABILITY RANKING — TEST")
print("=" * 110)

print("\nRequired Capability :", test_required_capability)
print("Incident Zone       :", test_incident_zone)

print("\nRanked Teams:")

display(
    ranking_test_df[
        [
            "Rank",
            "Team_ID",
            "Capability_Match",
            "Readiness_Level",
            "Zone_Relationship",
            "Vehicle_Available",
            "Personnel_Strength",
            "Capability_Score",
            "Readiness_Score",
            "Zone_Score",
            "Vehicle_Score",
            "Personnel_Score",
            "Suitability_Score"
        ]
    ]
)

if not ranking_test_df.empty:

    print("\nRecommended Primary Team:")
    print(
        ranking_test_df.iloc[0]["Team_ID"],
        "- Score:",
        ranking_test_df.iloc[0]["Suitability_Score"]
    )

    if len(ranking_test_df) > 1:
        print("\nRecommended Alternate Team:")
        print(
            ranking_test_df.iloc[1]["Team_ID"],
            "- Score:",
            ranking_test_df.iloc[1]["Suitability_Score"]
        )

print("\nExpected Result:")
print("RT-02 should rank FIRST because:")
print("- Personnel Safety is its PRIMARY capability")
print("- It is READY")
print("- It is already in Zone B")
print("- A vehicle is available")
print("- It has strong personnel strength")

print("\n" + "=" * 110)
print("TEAM SUITABILITY RANKING TEST COMPLETE")
print("=" * 110)

==============================================================================================================
RESPONSE TEAM SUITABILITY RANKING — TEST
==============================================================================================================

Required Capability : Personnel Safety
Incident Zone       : Zone B

Ranked Teams:

,Rank,Team_ID,Capability_Match,Readiness_Level,Zone_Relationship,Vehicle_Available,Personnel_Strength,Capability_Score,Readiness_Score,Zone_Score,Vehicle_Score,Personnel_Score,Suitability_Score
0,1,RT-02,PRIMARY,READY,SAME ZONE,True,7,40,25,20,10,5,100
1,2,RT-01,SECONDARY,READY,DIFFERENT ZONE,True,6,30,25,10,10,4,79
2,3,RT-05,PRIMARY,LIMITED,DIFFERENT ZONE,True,5,40,12,10,10,3,75

Recommended Primary Team:
RT-02 - Score: 100

Recommended Alternate Team:
RT-01 - Score: 79

Expected Result:
RT-02 should rank FIRST because:
- Personnel Safety is its PRIMARY capability
- It is READY
- It is already in Zone B
- A vehicle is available
- It has strong personnel strength

==============================================================================================================
TEAM SUITABILITY RANKING TEST COMPLETE
==============================================================================================================

In [12]:
# ======================================================================
# STEP 12 — DSS RESPONSE TO RESOURCE ALLOCATION BRIDGE
# ======================================================================

def get_required_capabilities(operational_response):
    """
    Convert an existing DSS operational-response category into
    its required primary and secondary capabilities.
    """

    match = response_capability_df[
        response_capability_df["Operational_Response"]
        == operational_response
    ]

    if match.empty:
        raise ValueError(
            f"No capability mapping found for operational response: "
            f"{operational_response}"
        )

    row = match.iloc[0]

    primary_capability = row[
        "Primary_Required_Capability"
    ]

    secondary_capabilities = [
        cap.strip()
        for cap in row[
            "Secondary_Required_Capabilities"
        ].split(";")
        if cap.strip()
    ]

    return {
        "Primary_Required_Capability": primary_capability,
        "Secondary_Required_Capabilities": secondary_capabilities
    }


def allocate_response_resource(
    operational_response,
    incident_zone,
    team_registry=response_team_df
):
    """
    Perform resource recommendation using an operational-response
    category produced by the existing DSS.

    Flow:
    DSS Operational Response
        ↓
    Required Capability
        ↓
    Eligibility Filtering
        ↓
    Suitability Ranking
        ↓
    Primary + Alternate Recommendation
    """

    capability_requirements = get_required_capabilities(
        operational_response
    )

    required_capability = capability_requirements[
        "Primary_Required_Capability"
    ]

    eligible_teams = filter_eligible_response_teams(
        team_registry,
        required_capability
    )

    ranked_teams = rank_eligible_response_teams(
        eligible_teams,
        required_capability,
        incident_zone
    )

    primary_team = None
    alternate_team = None

    if len(ranked_teams) >= 1:
        primary_team = ranked_teams.iloc[0].to_dict()

    if len(ranked_teams) >= 2:
        alternate_team = ranked_teams.iloc[1].to_dict()

    return {
        "Operational_Response": operational_response,
        "Required_Primary_Capability": required_capability,
        "Required_Secondary_Capabilities":
            capability_requirements[
                "Secondary_Required_Capabilities"
            ],
        "Incident_Zone": incident_zone,
        "Eligible_Team_Count": len(eligible_teams),
        "Primary_Recommendation": primary_team,
        "Alternate_Recommendation": alternate_team,
        "Full_Ranking": ranked_teams
    }


# ======================================================================
# TEST — USING AN EXISTING DSS RESPONSE CATEGORY
# ======================================================================

test_operational_response = (
    "Personnel Safety / Provost Response"
)

test_incident_zone = "Zone B"

allocation_test = allocate_response_resource(
    operational_response=test_operational_response,
    incident_zone=test_incident_zone
)

print("=" * 110)
print("DSS → RESOURCE ALLOCATION BRIDGE TEST")
print("=" * 110)

print("\nExisting DSS Operational Response:")
print(allocation_test["Operational_Response"])

print("\nDerived Primary Capability:")
print(allocation_test["Required_Primary_Capability"])

print("\nDerived Secondary Capabilities:")
for capability in allocation_test[
    "Required_Secondary_Capabilities"
]:
    print(" -", capability)

print("\nIncident Zone:")
print(allocation_test["Incident_Zone"])

print("\nEligible Team Count:")
print(allocation_test["Eligible_Team_Count"])


if allocation_test["Primary_Recommendation"]:

    primary = allocation_test[
        "Primary_Recommendation"
    ]

    print("\nPRIMARY RECOMMENDATION")
    print("-" * 50)
    print("Team ID           :", primary["Team_ID"])
    print("Team Name         :", primary["Team_Name"])
    print("Current Zone      :", primary["Current_Zone"])
    print("Capability Match  :", primary["Capability_Match"])
    print("Readiness         :", primary["Readiness_Level"])
    print(
        "Suitability Score :",
        f'{primary["Suitability_Score"]}/100'
    )


if allocation_test["Alternate_Recommendation"]:

    alternate = allocation_test[
        "Alternate_Recommendation"
    ]

    print("\nALTERNATE RECOMMENDATION")
    print("-" * 50)
    print("Team ID           :", alternate["Team_ID"])
    print("Team Name         :", alternate["Team_Name"])
    print("Current Zone      :", alternate["Current_Zone"])
    print("Capability Match  :", alternate["Capability_Match"])
    print("Readiness         :", alternate["Readiness_Level"])
    print(
        "Suitability Score :",
        f'{alternate["Suitability_Score"]}/100'
    )


print("\nFull Team Ranking:")
display(
    allocation_test["Full_Ranking"][
        [
            "Rank",
            "Team_ID",
            "Capability_Match",
            "Readiness_Level",
            "Zone_Relationship",
            "Suitability_Score"
        ]
    ]
)

print("\nIMPORTANT:")
print("This test starts from an operational-response category")
print("already produced by the existing DSS.")
print("The resource layer does NOT replace the existing DSS.")

print("\n" + "=" * 110)
print("DSS TO RESOURCE ALLOCATION BRIDGE TEST COMPLETE")
print("=" * 110)

==============================================================================================================
DSS → RESOURCE ALLOCATION BRIDGE TEST
==============================================================================================================

Existing DSS Operational Response:
Personnel Safety / Provost Response

Derived Primary Capability:
Personnel Safety

Derived Secondary Capabilities:
 - Incident Control
 - Medical Coordination

Incident Zone:
Zone B

Eligible Team Count:
3

PRIMARY RECOMMENDATION
--------------------------------------------------
Team ID           : RT-02
Team Name         : Response Team 02
Current Zone      : Zone B
Capability Match  : PRIMARY
Readiness         : READY
Suitability Score : 100/100

ALTERNATE RECOMMENDATION
--------------------------------------------------
Team ID           : RT-01
Team Name         : Response Team 01
Current Zone      : Zone A
Capability Match  : SECONDARY
Readiness         : READY
Suitability Score : 79/100

Full Team Ranking:

,Rank,Team_ID,Capability_Match,Readiness_Level,Zone_Relationship,Suitability_Score
0,1,RT-02,PRIMARY,READY,SAME ZONE,100
1,2,RT-01,SECONDARY,READY,DIFFERENT ZONE,79
2,3,RT-05,PRIMARY,LIMITED,DIFFERENT ZONE,75

IMPORTANT:
This test starts from an operational-response category
already produced by the existing DSS.
The resource layer does NOT replace the existing DSS.

==============================================================================================================
DSS TO RESOURCE ALLOCATION BRIDGE TEST COMPLETE
==============================================================================================================

In [13]:
# ======================================================================
# STEP 13 — DYNAMIC TEAM AVAILABILITY / FALLBACK TEST
# ======================================================================

# Create a temporary copy so the baseline registry is NOT modified
dynamic_test_registry = response_team_df.copy(deep=True)

# ----------------------------------------------------------------------
# Simulate RT-02 becoming assigned
# ----------------------------------------------------------------------

dynamic_test_registry.loc[
    dynamic_test_registry["Team_ID"] == "RT-02",
    "Status"
] = "ASSIGNED"

dynamic_test_registry.loc[
    dynamic_test_registry["Team_ID"] == "RT-02",
    "Current_Assignment"
] = "SIM-INC-DYNAMIC-TEST"

print("=" * 110)
print("DYNAMIC TEAM AVAILABILITY — FALLBACK TEST")
print("=" * 110)

print("\nSimulated State Change:")
print("RT-02 Status : ASSIGNED")
print("RT-02 is therefore no longer immediately deployable.")

# ----------------------------------------------------------------------
# Run the SAME DSS-derived allocation request
# ----------------------------------------------------------------------

fallback_test = allocate_response_resource(
    operational_response="Personnel Safety / Provost Response",
    incident_zone="Zone B",
    team_registry=dynamic_test_registry
)

# ----------------------------------------------------------------------
# Show recommendation
# ----------------------------------------------------------------------

if fallback_test["Primary_Recommendation"]:

    primary = fallback_test["Primary_Recommendation"]

    print("\nNEW PRIMARY RECOMMENDATION")
    print("-" * 50)
    print("Team ID           :", primary["Team_ID"])
    print("Current Zone      :", primary["Current_Zone"])
    print("Capability Match  :", primary["Capability_Match"])
    print("Readiness         :", primary["Readiness_Level"])
    print(
        "Suitability Score :",
        f'{primary["Suitability_Score"]}/100'
    )


if fallback_test["Alternate_Recommendation"]:

    alternate = fallback_test["Alternate_Recommendation"]

    print("\nNEW ALTERNATE RECOMMENDATION")
    print("-" * 50)
    print("Team ID           :", alternate["Team_ID"])
    print("Current Zone      :", alternate["Current_Zone"])
    print("Capability Match  :", alternate["Capability_Match"])
    print("Readiness         :", alternate["Readiness_Level"])
    print(
        "Suitability Score :",
        f'{alternate["Suitability_Score"]}/100'
    )

print("\nUpdated Eligible Ranking:")

display(
    fallback_test["Full_Ranking"][
        [
            "Rank",
            "Team_ID",
            "Capability_Match",
            "Readiness_Level",
            "Zone_Relationship",
            "Suitability_Score"
        ]
    ]
)

# ----------------------------------------------------------------------
# Validation
# ----------------------------------------------------------------------

recommended_team = (
    fallback_test["Primary_Recommendation"]["Team_ID"]
    if fallback_test["Primary_Recommendation"]
    else None
)

if recommended_team == "RT-02":
    print("\n✗ TEST FAILED: Assigned RT-02 was still recommended.")
else:
    print("\n✓ Assigned RT-02 was correctly excluded.")
    print("✓ The allocator automatically selected the next suitable team.")

print("\nIMPORTANT:")
print("The original Response Team Registry has NOT been modified.")
print("This was only a temporary dynamic-state simulation.")

print("\n" + "=" * 110)
print("DYNAMIC AVAILABILITY FALLBACK TEST COMPLETE")
print("=" * 110)

==============================================================================================================
DYNAMIC TEAM AVAILABILITY — FALLBACK TEST
==============================================================================================================

Simulated State Change:
RT-02 Status : ASSIGNED
RT-02 is therefore no longer immediately deployable.

NEW PRIMARY RECOMMENDATION
--------------------------------------------------
Team ID           : RT-01
Current Zone      : Zone A
Capability Match  : SECONDARY
Readiness         : READY
Suitability Score : 79/100

NEW ALTERNATE RECOMMENDATION
--------------------------------------------------
Team ID           : RT-05
Current Zone      : Zone E
Capability Match  : PRIMARY
Readiness         : LIMITED
Suitability Score : 75/100

Updated Eligible Ranking:

,Rank,Team_ID,Capability_Match,Readiness_Level,Zone_Relationship,Suitability_Score
0,1,RT-01,SECONDARY,READY,DIFFERENT ZONE,79
1,2,RT-05,PRIMARY,LIMITED,DIFFERENT ZONE,75

✓ Assigned RT-02 was correctly excluded.
✓ The allocator automatically selected the next suitable team.

IMPORTANT:
The original Response Team Registry has NOT been modified.
This was only a temporary dynamic-state simulation.

==============================================================================================================
DYNAMIC AVAILABILITY FALLBACK TEST COMPLETE
==============================================================================================================

In [14]:
# ======================================================================
# STEP 14 — NO DEPLOYABLE RESOURCE EDGE-CASE TEST
# ======================================================================

# Create a temporary registry copy.
# The baseline Response Team Registry will NOT be modified.

no_resource_test_registry = response_team_df.copy(deep=True)

# ----------------------------------------------------------------------
# Simulate all Controlled Substances teams becoming unavailable
# ----------------------------------------------------------------------

controlled_substance_teams = ["RT-06", "RT-10"]

no_resource_test_registry.loc[
    no_resource_test_registry["Team_ID"].isin(controlled_substance_teams),
    "Status"
] = "ASSIGNED"

print("=" * 110)
print("NO DEPLOYABLE RESOURCE — EDGE-CASE TEST")
print("=" * 110)

print("\nSimulated Condition:")
print("RT-06 : ASSIGNED")
print("RT-10 : ASSIGNED")

print(
    "\nTherefore no immediately deployable team should remain "
    "for Controlled Substances Response."
)

# ----------------------------------------------------------------------
# Run allocation request
# ----------------------------------------------------------------------

no_resource_test = allocate_response_resource(
    operational_response="Controlled Substances / Security Response",
    incident_zone="Zone F",
    team_registry=no_resource_test_registry
)

print("\nDSS Operational Response:")
print(no_resource_test["Operational_Response"])

print("\nRequired Primary Capability:")
print(no_resource_test["Required_Primary_Capability"])

print("\nEligible Team Count:")
print(no_resource_test["Eligible_Team_Count"])

# ----------------------------------------------------------------------
# Recommendation handling
# ----------------------------------------------------------------------

primary = no_resource_test["Primary_Recommendation"]
alternate = no_resource_test["Alternate_Recommendation"]

if primary is None:

    print("\nPRIMARY RECOMMENDATION")
    print("-" * 50)
    print("NO IMMEDIATELY DEPLOYABLE TEAM")

else:

    print("\nPRIMARY RECOMMENDATION")
    print("-" * 50)
    print(primary["Team_ID"])


if alternate is None:

    print("\nALTERNATE RECOMMENDATION")
    print("-" * 50)
    print("NO ALTERNATE DEPLOYABLE TEAM")

else:

    print("\nALTERNATE RECOMMENDATION")
    print("-" * 50)
    print(alternate["Team_ID"])


# ----------------------------------------------------------------------
# Validation
# ----------------------------------------------------------------------

if (
    no_resource_test["Eligible_Team_Count"] == 0
    and primary is None
    and alternate is None
):

    print("\n✓ No-resource condition handled correctly.")
    print("✓ System did NOT fabricate a team recommendation.")
    print("✓ Human operator escalation can be triggered later.")

else:

    print("\n✗ Edge-case validation FAILED.")

print("\nIMPORTANT:")
print("This condition should later appear in the dashboard as an")
print("operational resource warning rather than a software error.")

print("\nThe original Response Team Registry remains unchanged.")

print("\n" + "=" * 110)
print("NO DEPLOYABLE RESOURCE EDGE-CASE TEST COMPLETE")
print("=" * 110)

==============================================================================================================
NO DEPLOYABLE RESOURCE — EDGE-CASE TEST
==============================================================================================================

Simulated Condition:
RT-06 : ASSIGNED
RT-10 : ASSIGNED

Therefore no immediately deployable team should remain for Controlled Substances Response.

DSS Operational Response:
Controlled Substances / Security Response

Required Primary Capability:
Controlled Substances Response

Eligible Team Count:
0

PRIMARY RECOMMENDATION
--------------------------------------------------
NO IMMEDIATELY DEPLOYABLE TEAM

ALTERNATE RECOMMENDATION
--------------------------------------------------
NO ALTERNATE DEPLOYABLE TEAM

✓ No-resource condition handled correctly.
✓ System did NOT fabricate a team recommendation.
✓ Human operator escalation can be triggered later.

IMPORTANT:
This condition should later appear in the dashboard as an
operational resource warning rather than a software error.

The original Response Team Registry remains unchanged.

==============================================================================================================
NO DEPLOYABLE RESOURCE EDGE-CASE TEST COMPLETE
==============================================================================================================

In [15]:
# ======================================================================
# STEP 15 — RESPONSE TEAM ASSIGNMENT STATE MANAGEMENT
# ======================================================================

from datetime import datetime


def assign_response_team(
    team_registry,
    team_id,
    incident_id
):
    """
    Assign an AVAILABLE response team to a simulated incident.

    Returns a NEW registry copy.
    The original DataFrame is not modified in-place.
    """

    updated_registry = team_registry.copy(deep=True)

    team_match = updated_registry[
        updated_registry["Team_ID"] == team_id
    ]

    if team_match.empty:
        raise ValueError(
            f"Team ID '{team_id}' does not exist in the registry."
        )

    team_index = team_match.index[0]

    current_status = updated_registry.loc[
        team_index,
        "Status"
    ]

    readiness = updated_registry.loc[
        team_index,
        "Readiness_Level"
    ]

    if current_status != "AVAILABLE":
        raise ValueError(
            f"{team_id} cannot be assigned because its "
            f"current status is {current_status}."
        )

    if readiness == "UNAVAILABLE":
        raise ValueError(
            f"{team_id} cannot be assigned because its "
            "readiness level is UNAVAILABLE."
        )

    updated_registry.loc[
        team_index,
        "Status"
    ] = "ASSIGNED"

    updated_registry.loc[
        team_index,
        "Current_Assignment"
    ] = incident_id

    updated_registry.loc[
        team_index,
        "Last_Updated"
    ] = datetime.now()

    return updated_registry


def release_response_team(
    team_registry,
    team_id
):
    """
    Release a previously ASSIGNED response team.

    Returns a NEW registry copy.
    """

    updated_registry = team_registry.copy(deep=True)

    team_match = updated_registry[
        updated_registry["Team_ID"] == team_id
    ]

    if team_match.empty:
        raise ValueError(
            f"Team ID '{team_id}' does not exist in the registry."
        )

    team_index = team_match.index[0]

    current_status = updated_registry.loc[
        team_index,
        "Status"
    ]

    if current_status != "ASSIGNED":
        raise ValueError(
            f"{team_id} cannot be released because its "
            f"current status is {current_status}."
        )

    updated_registry.loc[
        team_index,
        "Status"
    ] = "AVAILABLE"

    updated_registry.loc[
        team_index,
        "Current_Assignment"
    ] = "None"

    updated_registry.loc[
        team_index,
        "Last_Updated"
    ] = datetime.now()

    return updated_registry


# ======================================================================
# TEST — ASSIGN AND RELEASE RT-02
# ======================================================================

state_test_registry = response_team_df.copy(deep=True)

print("=" * 110)
print("RESPONSE TEAM ASSIGNMENT STATE MANAGEMENT TEST")
print("=" * 110)

print("\nINITIAL STATE")

initial_rt02 = state_test_registry[
    state_test_registry["Team_ID"] == "RT-02"
].iloc[0]

print("Team ID            :", initial_rt02["Team_ID"])
print("Status             :", initial_rt02["Status"])
print(
    "Current Assignment :",
    initial_rt02["Current_Assignment"]
)

# ----------------------------------------------------------------------
# Assign team
# ----------------------------------------------------------------------

state_test_registry = assign_response_team(
    team_registry=state_test_registry,
    team_id="RT-02",
    incident_id="SIM-INC-0100"
)

assigned_rt02 = state_test_registry[
    state_test_registry["Team_ID"] == "RT-02"
].iloc[0]

print("\nAFTER ASSIGNMENT")
print("Team ID            :", assigned_rt02["Team_ID"])
print("Status             :", assigned_rt02["Status"])
print(
    "Current Assignment :",
    assigned_rt02["Current_Assignment"]
)

# ----------------------------------------------------------------------
# Confirm assigned team is excluded from a new allocation
# ----------------------------------------------------------------------

post_assignment_allocation = allocate_response_resource(
    operational_response="Personnel Safety / Provost Response",
    incident_zone="Zone B",
    team_registry=state_test_registry
)

next_team = (
    post_assignment_allocation[
        "Primary_Recommendation"
    ]["Team_ID"]
    if post_assignment_allocation[
        "Primary_Recommendation"
    ]
    else None
)

print("\nNEXT ALLOCATION AFTER RT-02 ASSIGNMENT")
print("Recommended Team :", next_team)

# ----------------------------------------------------------------------
# Release team
# ----------------------------------------------------------------------

state_test_registry = release_response_team(
    team_registry=state_test_registry,
    team_id="RT-02"
)

released_rt02 = state_test_registry[
    state_test_registry["Team_ID"] == "RT-02"
].iloc[0]

print("\nAFTER RELEASE")
print("Team ID            :", released_rt02["Team_ID"])
print("Status             :", released_rt02["Status"])
print(
    "Current Assignment :",
    released_rt02["Current_Assignment"]
)

# ----------------------------------------------------------------------
# Validation
# ----------------------------------------------------------------------

assignment_valid = (
    assigned_rt02["Status"] == "ASSIGNED"
    and assigned_rt02["Current_Assignment"]
    == "SIM-INC-0100"
)

fallback_valid = (
    next_team is not None
    and next_team != "RT-02"
)

release_valid = (
    released_rt02["Status"] == "AVAILABLE"
    and released_rt02["Current_Assignment"] == "None"
)

print("\nValidation")
print("-" * 60)

print(
    "Assignment State Update :",
    "✓ PASS" if assignment_valid else "✗ FAIL"
)

print(
    "Assigned Team Exclusion :",
    "✓ PASS" if fallback_valid else "✗ FAIL"
)

print(
    "Team Release            :",
    "✓ PASS" if release_valid else "✗ FAIL"
)

if assignment_valid and fallback_valid and release_valid:
    print(
        "\n✓ RESPONSE TEAM STATE MANAGEMENT "
        "TEST PASSED."
    )
else:
    print(
        "\n✗ RESPONSE TEAM STATE MANAGEMENT "
        "TEST FAILED."
    )

print("\nIMPORTANT:")
print(
    "The baseline Response_Team_Registry.csv "
    "was NOT modified by this test."
)

print("\n" + "=" * 110)
print("RESPONSE TEAM ASSIGNMENT STATE MANAGEMENT TEST COMPLETE")
print("=" * 110)

==============================================================================================================
RESPONSE TEAM ASSIGNMENT STATE MANAGEMENT TEST
==============================================================================================================

INITIAL STATE
Team ID            : RT-02
Status             : AVAILABLE
Current Assignment : None

AFTER ASSIGNMENT
Team ID            : RT-02
Status             : ASSIGNED
Current Assignment : SIM-INC-0100

NEXT ALLOCATION AFTER RT-02 ASSIGNMENT
Recommended Team : RT-01

AFTER RELEASE
Team ID            : RT-02
Status             : AVAILABLE
Current Assignment : None

Validation
------------------------------------------------------------
Assignment State Update : ✓ PASS
Assigned Team Exclusion : ✓ PASS
Team Release            : ✓ PASS

✓ RESPONSE TEAM STATE MANAGEMENT TEST PASSED.

IMPORTANT:
The baseline Response_Team_Registry.csv was NOT modified by this test.

==============================================================================================================
RESPONSE TEAM ASSIGNMENT STATE MANAGEMENT TEST COMPLETE
==============================================================================================================

In [16]:
# ======================================================================
# STEP 16 — HUMAN OPERATOR CONFIRM / OVERRIDE LOGIC
# ======================================================================

from datetime import datetime
import uuid


def process_operator_decision(
    allocation_result,
    team_registry,
    operator_uid,
    action,
    selected_team_id=None,
    override_reason=None,
    incident_id=None
):
    """
    Process a human operator decision after resource recommendation.

    action:
        CONFIRM  -> accept DSS primary recommendation
        OVERRIDE -> select another currently eligible team

    Returns:
        decision_record
        updated_registry
    """

    action = str(action).strip().upper()

    if action not in ["CONFIRM", "OVERRIDE"]:
        raise ValueError(
            "Operator action must be CONFIRM or OVERRIDE."
        )

    recommended_team = allocation_result[
        "Primary_Recommendation"
    ]

    if recommended_team is None:
        raise ValueError(
            "No primary team recommendation exists. "
            "Operator confirmation/override cannot proceed."
        )

    recommended_team_id = recommended_team["Team_ID"]

    # ------------------------------------------------------------------
    # CONFIRM
    # ------------------------------------------------------------------

    if action == "CONFIRM":

        final_team_id = recommended_team_id
        decision_type = "CONFIRMED"
        override_reason_final = None

    # ------------------------------------------------------------------
    # OVERRIDE
    # ------------------------------------------------------------------

    else:

        if selected_team_id is None:
            raise ValueError(
                "selected_team_id is required for OVERRIDE."
            )

        if selected_team_id == recommended_team_id:
            raise ValueError(
                "Override team cannot be the same as "
                "the recommended team."
            )

        ranked_teams = allocation_result["Full_Ranking"]

        eligible_team_ids = set(
            ranked_teams["Team_ID"].tolist()
        )

        if selected_team_id not in eligible_team_ids:
            raise ValueError(
                f"{selected_team_id} is not currently an "
                "eligible deployment option."
            )

        if (
            override_reason is None
            or not str(override_reason).strip()
        ):
            raise ValueError(
                "An override reason is required."
            )

        final_team_id = selected_team_id
        decision_type = "OVERRIDDEN"
        override_reason_final = str(
            override_reason
        ).strip()

    # ------------------------------------------------------------------
    # Incident / Decision IDs
    # ------------------------------------------------------------------

    if incident_id is None:
        incident_id = (
            "SIM-INC-"
            + datetime.now().strftime("%Y%m%d%H%M%S")
        )

    decision_id = (
        "DEC-"
        + uuid.uuid4().hex[:10].upper()
    )

    decision_timestamp = datetime.now()

    # ------------------------------------------------------------------
    # Assign final human-selected team
    # ------------------------------------------------------------------

    updated_registry = assign_response_team(
        team_registry=team_registry,
        team_id=final_team_id,
        incident_id=incident_id
    )

    # ------------------------------------------------------------------
    # Find selected team's ranking information
    # ------------------------------------------------------------------

    selected_row = allocation_result[
        "Full_Ranking"
    ][
        allocation_result["Full_Ranking"]["Team_ID"]
        == final_team_id
    ].iloc[0]

    # ------------------------------------------------------------------
    # Decision record
    # ------------------------------------------------------------------

    decision_record = {
        "Decision_ID": decision_id,
        "Incident_ID": incident_id,
        "Timestamp": decision_timestamp,
        "Operator_UID": operator_uid,

        "Operational_Response":
            allocation_result["Operational_Response"],

        "Incident_Zone":
            allocation_result["Incident_Zone"],

        "Required_Capability":
            allocation_result[
                "Required_Primary_Capability"
            ],

        "Recommended_Team_ID":
            recommended_team_id,

        "Recommended_Team_Score":
            recommended_team[
                "Suitability_Score"
            ],

        "Operator_Action":
            decision_type,

        "Selected_Team_ID":
            final_team_id,

        "Selected_Team_Score":
            selected_row[
                "Suitability_Score"
            ],

        "Override_Reason":
            override_reason_final
    }

    return decision_record, updated_registry


# ======================================================================
# TEST 1 — OPERATOR CONFIRMS DSS RECOMMENDATION
# ======================================================================

confirm_test_registry = response_team_df.copy(deep=True)

confirm_allocation = allocate_response_resource(
    operational_response="Personnel Safety / Provost Response",
    incident_zone="Zone B",
    team_registry=confirm_test_registry
)

confirm_record, confirm_updated_registry = (
    process_operator_decision(
        allocation_result=confirm_allocation,
        team_registry=confirm_test_registry,
        operator_uid="TEST-OPERATOR-01",
        action="CONFIRM",
        incident_id="SIM-INC-CONFIRM-001"
    )
)

print("=" * 110)
print("HUMAN OPERATOR DECISION TEST")
print("=" * 110)

print("\nTEST 1 — CONFIRM RECOMMENDATION")
print("-" * 60)

print(
    "Recommended Team :",
    confirm_record["Recommended_Team_ID"]
)

print(
    "Selected Team    :",
    confirm_record["Selected_Team_ID"]
)

print(
    "Operator Action  :",
    confirm_record["Operator_Action"]
)

print(
    "Decision ID      :",
    confirm_record["Decision_ID"]
)

confirmed_team_status = confirm_updated_registry.loc[
    confirm_updated_registry["Team_ID"]
    == confirm_record["Selected_Team_ID"],
    "Status"
].iloc[0]

print(
    "Final Team Status:",
    confirmed_team_status
)


# ======================================================================
# TEST 2 — OPERATOR OVERRIDES DSS RECOMMENDATION
# ======================================================================

override_test_registry = response_team_df.copy(deep=True)

override_allocation = allocate_response_resource(
    operational_response="Personnel Safety / Provost Response",
    incident_zone="Zone B",
    team_registry=override_test_registry
)

override_record, override_updated_registry = (
    process_operator_decision(
        allocation_result=override_allocation,
        team_registry=override_test_registry,
        operator_uid="TEST-OPERATOR-01",
        action="OVERRIDE",
        selected_team_id="RT-01",
        override_reason=(
            "Operator selected alternate team for "
            "simulated operational coordination."
        ),
        incident_id="SIM-INC-OVERRIDE-001"
    )
)

print("\nTEST 2 — OVERRIDE RECOMMENDATION")
print("-" * 60)

print(
    "Recommended Team :",
    override_record["Recommended_Team_ID"]
)

print(
    "Selected Team    :",
    override_record["Selected_Team_ID"]
)

print(
    "Operator Action  :",
    override_record["Operator_Action"]
)

print(
    "Override Reason  :",
    override_record["Override_Reason"]
)

print(
    "Decision ID      :",
    override_record["Decision_ID"]
)

overridden_team_status = (
    override_updated_registry.loc[
        override_updated_registry["Team_ID"]
        == override_record["Selected_Team_ID"],
        "Status"
    ].iloc[0]
)

print(
    "Final Team Status:",
    overridden_team_status
)


# ======================================================================
# VALIDATION
# ======================================================================

confirm_pass = (
    confirm_record["Recommended_Team_ID"]
    == confirm_record["Selected_Team_ID"]
    and confirm_record["Operator_Action"]
    == "CONFIRMED"
    and confirmed_team_status == "ASSIGNED"
)

override_pass = (
    override_record["Recommended_Team_ID"]
    != override_record["Selected_Team_ID"]
    and override_record["Operator_Action"]
    == "OVERRIDDEN"
    and overridden_team_status == "ASSIGNED"
    and override_record["Override_Reason"] is not None
)

print("\nValidation")
print("-" * 60)

print(
    "Operator Confirmation :",
    "✓ PASS" if confirm_pass else "✗ FAIL"
)

print(
    "Operator Override     :",
    "✓ PASS" if override_pass else "✗ FAIL"
)

if confirm_pass and override_pass:
    print(
        "\n✓ HUMAN-IN-THE-LOOP DECISION LOGIC TEST PASSED."
    )
else:
    print(
        "\n✗ HUMAN-IN-THE-LOOP DECISION LOGIC TEST FAILED."
    )

print("\nIMPORTANT:")
print("The DSS only recommends the response resource.")
print("The human operator determines the final selected team.")
print("Override decisions require an explicit reason.")
print("The baseline Response_Team_Registry.csv remains unchanged.")

print("\n" + "=" * 110)
print("HUMAN OPERATOR CONFIRM / OVERRIDE TEST COMPLETE")
print("=" * 110)

==============================================================================================================
HUMAN OPERATOR DECISION TEST
==============================================================================================================

TEST 1 — CONFIRM RECOMMENDATION
------------------------------------------------------------
Recommended Team : RT-02
Selected Team    : RT-02
Operator Action  : CONFIRMED
Decision ID      : DEC-FA1159E1EF
Final Team Status: ASSIGNED

TEST 2 — OVERRIDE RECOMMENDATION
------------------------------------------------------------
Recommended Team : RT-02
Selected Team    : RT-01
Operator Action  : OVERRIDDEN
Override Reason  : Operator selected alternate team for simulated operational coordination.
Decision ID      : DEC-0BF9B8AB8F
Final Team Status: ASSIGNED

Validation
------------------------------------------------------------
Operator Confirmation : ✓ PASS
Operator Override     : ✓ PASS

✓ HUMAN-IN-THE-LOOP DECISION LOGIC TEST PASSED.

IMPORTANT:
The DSS only recommends the response resource.
The human operator determines the final selected team.
Override decisions require an explicit reason.
The baseline Response_Team_Registry.csv remains unchanged.

==============================================================================================================
HUMAN OPERATOR CONFIRM / OVERRIDE TEST COMPLETE
==============================================================================================================

In [17]:
# ======================================================================
# STEP 17 — RESOURCE ALLOCATION AUDIT LOG
# ======================================================================

RESOURCE_ALLOCATION_AUDIT_PATH = (
    LOGS_DIR / "Response_Team_Allocation_Audit_Log.csv"
)


def append_resource_allocation_audit(
    decision_record,
    audit_path=RESOURCE_ALLOCATION_AUDIT_PATH
):
    """
    Append one human-approved resource-allocation decision
    to the persistent audit log.
    """

    audit_row = pd.DataFrame([decision_record])

    if audit_path.exists():

        existing_log = pd.read_csv(audit_path)

        updated_log = pd.concat(
            [existing_log, audit_row],
            ignore_index=True
        )

    else:

        updated_log = audit_row.copy()

    updated_log.to_csv(
        audit_path,
        index=False
    )

    return updated_log


# ======================================================================
# TEST — WRITE CONFIRM + OVERRIDE RECORDS
# ======================================================================

print("=" * 110)
print("RESOURCE ALLOCATION AUDIT LOG TEST")
print("=" * 110)

# Use a TEMPORARY test audit path so we do not pollute
# the future production audit log with development records.

TEST_AUDIT_PATH = (
    LOGS_DIR / "Response_Team_Allocation_Audit_Log_TEST.csv"
)

# Remove previous test file if this cell is rerun
if TEST_AUDIT_PATH.exists():
    TEST_AUDIT_PATH.unlink()

# ----------------------------------------------------------------------
# Append CONFIRM record
# ----------------------------------------------------------------------

test_audit_df = append_resource_allocation_audit(
    decision_record=confirm_record,
    audit_path=TEST_AUDIT_PATH
)

print("\nAfter CONFIRM record:")
print("Audit Rows :", len(test_audit_df))

# ----------------------------------------------------------------------
# Append OVERRIDE record
# ----------------------------------------------------------------------

test_audit_df = append_resource_allocation_audit(
    decision_record=override_record,
    audit_path=TEST_AUDIT_PATH
)

print("\nAfter OVERRIDE record:")
print("Audit Rows :", len(test_audit_df))

# ----------------------------------------------------------------------
# Reload from disk
# ----------------------------------------------------------------------

reloaded_test_audit = pd.read_csv(
    TEST_AUDIT_PATH
)

print("\nPersisted Audit Records:")
display(
    reloaded_test_audit[
        [
            "Decision_ID",
            "Incident_ID",
            "Operator_UID",
            "Operational_Response",
            "Incident_Zone",
            "Recommended_Team_ID",
            "Operator_Action",
            "Selected_Team_ID",
            "Override_Reason"
        ]
    ]
)

# ----------------------------------------------------------------------
# Validation
# ----------------------------------------------------------------------

row_count_pass = (
    len(reloaded_test_audit) == 2
)

confirm_record_pass = (
    "CONFIRMED"
    in reloaded_test_audit[
        "Operator_Action"
    ].values
)

override_record_pass = (
    "OVERRIDDEN"
    in reloaded_test_audit[
        "Operator_Action"
    ].values
)

override_reason_pass = (
    reloaded_test_audit.loc[
        reloaded_test_audit["Operator_Action"]
        == "OVERRIDDEN",
        "Override_Reason"
    ].notna().all()
)

print("\nValidation")
print("-" * 60)

print(
    "Persistent Row Count       :",
    "✓ PASS" if row_count_pass else "✗ FAIL"
)

print(
    "Confirmation Audit Record  :",
    "✓ PASS" if confirm_record_pass else "✗ FAIL"
)

print(
    "Override Audit Record      :",
    "✓ PASS" if override_record_pass else "✗ FAIL"
)

print(
    "Override Reason Retained   :",
    "✓ PASS" if override_reason_pass else "✗ FAIL"
)

if (
    row_count_pass
    and confirm_record_pass
    and override_record_pass
    and override_reason_pass
):
    print(
        "\n✓ RESOURCE ALLOCATION AUDIT LOG TEST PASSED."
    )
else:
    print(
        "\n✗ RESOURCE ALLOCATION AUDIT LOG TEST FAILED."
    )

print("\nProduction Audit Path:")
print(RESOURCE_ALLOCATION_AUDIT_PATH)

print("\nIMPORTANT:")
print(
    "The production audit log has NOT been populated "
    "with these development-test records."
)

print(
    "The TEST audit CSV may be deleted after validation."
)

print("\n" + "=" * 110)
print("RESOURCE ALLOCATION AUDIT LOG TEST COMPLETE")
print("=" * 110)

==============================================================================================================
RESOURCE ALLOCATION AUDIT LOG TEST
==============================================================================================================

After CONFIRM record:
Audit Rows : 1

After OVERRIDE record:
Audit Rows : 2

Persisted Audit Records:

,Decision_ID,Incident_ID,Operator_UID,Operational_Response,Incident_Zone,Recommended_Team_ID,Operator_Action,Selected_Team_ID,Override_Reason
0,DEC-FA1159E1EF,SIM-INC-CONFIRM-001,TEST-OPERATOR-01,Personnel Safety / Provost Response,Zone B,RT-02,CONFIRMED,RT-02,NaN
1,DEC-0BF9B8AB8F,SIM-INC-OVERRIDE-001,TEST-OPERATOR-01,Personnel Safety / Provost Response,Zone B,RT-02,OVERRIDDEN,RT-01,Operator selected alternate team for simulated...

Validation
------------------------------------------------------------
Persistent Row Count       : ✓ PASS
Confirmation Audit Record  : ✓ PASS
Override Audit Record      : ✓ PASS
Override Reason Retained   : ✓ PASS

✓ RESOURCE ALLOCATION AUDIT LOG TEST PASSED.

Production Audit Path:
/content/drive/MyDrive/Army_Provost_ML_Project/Logs/Response_Team_Allocation_Audit_Log.csv

IMPORTANT:
The production audit log has NOT been populated with these development-test records.
The TEST audit CSV may be deleted after validation.

==============================================================================================================
RESOURCE ALLOCATION AUDIT LOG TEST COMPLETE
==============================================================================================================