<a href="https://colab.research.google.com/github/arnavon2005/Army_Provost_ML_Project/blob/main/Notebooks/Army_Provost_ML_Project_Main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# ==========================================================
# STEP 1 : MOUNT GOOGLE DRIVE
# ==========================================================

from google.colab import drive
drive.mount('/content/drive')

# ==========================================================
# IMPORT REQUIRED LIBRARY
# ==========================================================

import os

# ==========================================================
# DEFINE PROJECT ROOT
# ==========================================================

PROJECT_ROOT = "/content/drive/MyDrive/Army_Provost_ML_Project"

# ==========================================================
# CREATE PROJECT FOLDERS
# ==========================================================

folders = [
    "Datasets/Raw",
    "Datasets/Cleaned",
    "Notebooks",
    "Models",
    "Figures",
    "Reports",
    "Outputs",
    "Logs"
]

for folder in folders:
    os.makedirs(os.path.join(PROJECT_ROOT, folder), exist_ok=True)

print("=" * 60)
print("PROJECT FOLDER STRUCTURE CREATED SUCCESSFULLY")
print("=" * 60)

# ==========================================================
# DISPLAY FOLDER STRUCTURE
# ==========================================================

for root, dirs, files in os.walk(PROJECT_ROOT):
    level = root.replace(PROJECT_ROOT, '').count(os.sep)
    indent = ' ' * 4 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = ' ' * 4 * (level + 1)
    for file in files:
        print(f"{subindent}{file}")

Mounted at /content/drive
============================================================
PROJECT FOLDER STRUCTURE CREATED SUCCESSFULLY
============================================================
Army_Provost_ML_Project/
    Datasets/
        Raw/
            Crimes_-_2001_to_Present_20260729.csv
            Police_Dispatched_Incidents_20260729.csv
        Cleaned/
    Notebooks/
        Army_Provost_ML_Project_Main.ipynb
    Models/
    Figures/
    Reports/
    Outputs/
    Logs/

In [3]:
# ==========================================================
# STEP 2 : VERIFY GOOGLE COLAB ENVIRONMENT
# ==========================================================

import os
import platform
import sys
import subprocess

# ==========================================================
# PYTHON VERSION
# ==========================================================

print("=" * 70)
print("PYTHON INFORMATION")
print("=" * 70)

print(f"Python Version : {sys.version}")

# ==========================================================
# OPERATING SYSTEM
# ==========================================================

print("\n" + "=" * 70)
print("OPERATING SYSTEM")
print("=" * 70)

print(f"Platform : {platform.platform()}")
print(f"System   : {platform.system()}")
print(f"Release  : {platform.release()}")

# ==========================================================
# CURRENT WORKING DIRECTORY
# ==========================================================

print("\n" + "=" * 70)
print("CURRENT WORKING DIRECTORY")
print("=" * 70)

print(os.getcwd())

# ==========================================================
# CHECK GPU AVAILABILITY
# ==========================================================

print("\n" + "=" * 70)
print("RUNTIME TYPE")
print("=" * 70)

try:
    gpu_info = subprocess.check_output("nvidia-smi", shell=True).decode()
    print("GPU Runtime Detected\n")
    print(gpu_info)
except:
    print("No GPU detected.")
    print("Current Runtime : CPU")

# ==========================================================
# RAM INFORMATION
# ==========================================================

print("\n" + "=" * 70)
print("SYSTEM MEMORY")
print("=" * 70)

with open('/proc/meminfo') as f:
    memory = f.readlines()

for line in memory[:5]:
    print(line.strip())

# ==========================================================
# CPU INFORMATION
# ==========================================================

print("\n" + "=" * 70)
print("CPU INFORMATION")
print("=" * 70)

cpu_info = subprocess.check_output("lscpu", shell=True).decode()

for line in cpu_info.split("\n")[:15]:
    print(line)

# ==========================================================
# IMPORTANT LIBRARIES
# ==========================================================

print("\n" + "=" * 70)
print("IMPORTANT LIBRARIES")
print("=" * 70)

libraries = [
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "sklearn",
    "joblib"
]

for lib in libraries:
    try:
        module = __import__(lib)
        print(f"{lib:<12} Version : {module.__version__}")
    except:
        print(f"{lib:<12} Not Installed")

======================================================================
PYTHON INFORMATION
======================================================================
Python Version : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

======================================================================
OPERATING SYSTEM
======================================================================
Platform : Linux-6.6.122+-x86_64-with-glibc2.35
System   : Linux
Release  : 6.6.122+

======================================================================
CURRENT WORKING DIRECTORY
======================================================================
/content

======================================================================
RUNTIME TYPE
======================================================================
No GPU detected.
Current Runtime : CPU

======================================================================
SYSTEM MEMORY
======================================================================
MemTotal:       13286944 kB
MemFree:         8901564 kB
MemAvailable:   12023448 kB
Buffers:          117960 kB
Cached:          3202384 kB

======================================================================
CPU INFORMATION
======================================================================
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           46 bits physical, 48 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  2
On-line CPU(s) list:                     0,1
Vendor ID:                               GenuineIntel
Model name:                              Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                              6
Model:                                   79
Thread(s) per core:                      2
Core(s) per socket:                      1
Socket(s):                               1
Stepping:                                0
BogoMIPS:                                4399.99

======================================================================
IMPORTANT LIBRARIES
======================================================================
numpy        Version : 2.0.2
pandas       Version : 2.2.2
matplotlib   Version : 3.10.0
seaborn      Version : 0.13.2
sklearn      Version : 1.6.1
joblib       Version : 1.5.3

In [4]:
# ==========================================================
# STEP 3 : NOTEBOOK CONFIGURATION
# ==========================================================

import os
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================================
# PROJECT PATHS
# ==========================================================

PROJECT_ROOT = "/content/drive/MyDrive/Army_Provost_ML_Project"

RAW_DATA_PATH = os.path.join(PROJECT_ROOT, "Datasets", "Raw")
CLEAN_DATA_PATH = os.path.join(PROJECT_ROOT, "Datasets", "Cleaned")
MODEL_PATH = os.path.join(PROJECT_ROOT, "Models")
FIGURE_PATH = os.path.join(PROJECT_ROOT, "Figures")
REPORT_PATH = os.path.join(PROJECT_ROOT, "Reports")
OUTPUT_PATH = os.path.join(PROJECT_ROOT, "Outputs")
LOG_PATH = os.path.join(PROJECT_ROOT, "Logs")

# ==========================================================
# PANDAS DISPLAY SETTINGS
# ==========================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 150)
pd.set_option("display.max_colwidth", 100)

# Display floats with 2 decimal places
pd.options.display.float_format = "{:.2f}".format

# ==========================================================
# WARNING SETTINGS
# ==========================================================

warnings.filterwarnings("ignore")

# ==========================================================
# MATPLOTLIB SETTINGS
# ==========================================================

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

# ==========================================================
# RANDOM SEED
# ==========================================================

RANDOM_STATE = 42

np.random.seed(RANDOM_STATE)

# ==========================================================
# CONFIRM CONFIGURATION
# ==========================================================

print("=" * 70)
print("NOTEBOOK CONFIGURATION COMPLETED")
print("=" * 70)

print(f"Project Root      : {PROJECT_ROOT}")
print(f"Raw Dataset Path  : {RAW_DATA_PATH}")
print(f"Clean Dataset Path: {CLEAN_DATA_PATH}")
print(f"Model Path        : {MODEL_PATH}")
print(f"Figure Path       : {FIGURE_PATH}")
print(f"Reports Path      : {REPORT_PATH}")
print(f"Outputs Path      : {OUTPUT_PATH}")
print(f"Logs Path         : {LOG_PATH}")
print(f"Random Seed       : {RANDOM_STATE}")

======================================================================
NOTEBOOK CONFIGURATION COMPLETED
======================================================================
Project Root      : /content/drive/MyDrive/Army_Provost_ML_Project
Raw Dataset Path  : /content/drive/MyDrive/Army_Provost_ML_Project/Datasets/Raw
Clean Dataset Path: /content/drive/MyDrive/Army_Provost_ML_Project/Datasets/Cleaned
Model Path        : /content/drive/MyDrive/Army_Provost_ML_Project/Models
Figure Path       : /content/drive/MyDrive/Army_Provost_ML_Project/Figures
Reports Path      : /content/drive/MyDrive/Army_Provost_ML_Project/Reports
Outputs Path      : /content/drive/MyDrive/Army_Provost_ML_Project/Outputs
Logs Path         : /content/drive/MyDrive/Army_Provost_ML_Project/Logs
Random Seed       : 42

In [5]:
# ==========================================================
# STEP 4 : VERIFY RAW DATASETS
# ==========================================================

import os

print("=" * 80)
print("VERIFYING RAW DATASETS")
print("=" * 80)

# Check whether the raw dataset folder exists
if not os.path.exists(RAW_DATA_PATH):
    print(f"❌ Folder not found: {RAW_DATA_PATH}")
else:
    print(f"✅ Raw dataset folder found:\n{RAW_DATA_PATH}\n")

    files = os.listdir(RAW_DATA_PATH)

    if len(files) == 0:
        print("❌ No files found in the Raw dataset folder.")
    else:
        print("Files detected:\n")

        for file in sorted(files):
            file_path = os.path.join(RAW_DATA_PATH, file)

            size_mb = os.path.getsize(file_path) / (1024 * 1024)

            print(f"• {file}")
            print(f"  Size : {size_mb:.2f} MB\n")

================================================================================
VERIFYING RAW DATASETS
================================================================================
✅ Raw dataset folder found:
/content/drive/MyDrive/Army_Provost_ML_Project/Datasets/Raw

Files detected:

• Crimes_-_2001_to_Present_20260729.csv
  Size : 2280.56 MB

• Police_Dispatched_Incidents_20260729.csv
  Size : 561.95 MB

In [6]:
# ==========================================================
# STEP 5 : IMPORT DATASETS
# ==========================================================

import os
import time
import pandas as pd

# ==========================================================
# DATASET FILE PATHS
# ==========================================================

CHICAGO_FILE = os.path.join(
    RAW_DATA_PATH,
    "Crimes_-_2001_to_Present_20260729.csv"
)

MONTGOMERY_FILE = os.path.join(
    RAW_DATA_PATH,
    "Police_Dispatched_Incidents_20260729.csv"
)

# ==========================================================
# VERIFY FILES
# ==========================================================

print("=" * 70)
print("VERIFYING DATASET FILES")
print("=" * 70)

assert os.path.exists(CHICAGO_FILE), f"Chicago dataset not found:\n{CHICAGO_FILE}"
assert os.path.exists(MONTGOMERY_FILE), f"Montgomery dataset not found:\n{MONTGOMERY_FILE}"

print("✅ Chicago Crimes dataset found.")
print("✅ Montgomery Police dataset found.")

# ==========================================================
# LOAD CHICAGO CRIMES DATASET
# ==========================================================

print("\nLoading Chicago Crimes dataset...")

start_time = time.time()

chicago_df = pd.read_csv(
    CHICAGO_FILE,
    low_memory=False
)

end_time = time.time()

print(f"Loaded successfully in {end_time - start_time:.2f} seconds.")

# ==========================================================
# LOAD MONTGOMERY DATASET
# ==========================================================

print("\nLoading Montgomery Police Dispatch dataset...")

start_time = time.time()

montgomery_df = pd.read_csv(
    MONTGOMERY_FILE,
    low_memory=False
)

end_time = time.time()

print(f"Loaded successfully in {end_time - start_time:.2f} seconds.")

# ==========================================================
# CONFIRM SUCCESS
# ==========================================================

print("\n" + "=" * 70)
print("DATASETS LOADED SUCCESSFULLY")
print("=" * 70)

======================================================================
VERIFYING DATASET FILES
======================================================================
✅ Chicago Crimes dataset found.
✅ Montgomery Police dataset found.

Loading Chicago Crimes dataset...
Loaded successfully in 85.36 seconds.

Loading Montgomery Police Dispatch dataset...
Loaded successfully in 31.09 seconds.

======================================================================
DATASETS LOADED SUCCESSFULLY
======================================================================

In [7]:
# ==========================================================
# STEP 6 : BASIC DATASET OVERVIEW
# ==========================================================

def dataset_overview(df, dataset_name):
    """
    Display basic information about a dataset.
    """

    print("=" * 80)
    print(f"{dataset_name.upper()} DATASET OVERVIEW")
    print("=" * 80)

    # Shape
    print(f"\nShape:")
    print(f"Rows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]}")

    # Memory Usage
    memory_mb = df.memory_usage(deep=True).sum() / (1024 ** 2)

    print(f"\nMemory Usage:")
    print(f"{memory_mb:.2f} MB")

    # Column Information
    print("\nColumns and Data Types:\n")

    info_df = pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.astype(str)
    })

    print(info_df.to_string(index=False))

    print("\n")


# ==========================================================
# CHICAGO DATASET
# ==========================================================

dataset_overview(
    chicago_df,
    "Chicago Crimes"
)

# ==========================================================
# MONTGOMERY DATASET
# ==========================================================

dataset_overview(
    montgomery_df,
    "Montgomery Police Dispatch"
)

================================================================================
CHICAGO CRIMES DATASET OVERVIEW
================================================================================

Shape:
Rows    : 8,602,734
Columns : 22

Memory Usage:
5862.23 MB

Columns and Data Types:

              Column Data Type
                  ID     int64
         Case Number    object
                Date    object
               Block    object
                IUCR    object
        Primary Type    object
         Description    object
Location Description    object
              Arrest      bool
            Domestic      bool
                Beat     int64
            District   float64
                Ward   float64
      Community Area   float64
            FBI Code    object
        X Coordinate   float64
        Y Coordinate   float64
                Year     int64
          Updated On    object
            Latitude   float64
           Longitude   float64
            Location    object


================================================================================
MONTGOMERY POLICE DISPATCH DATASET OVERVIEW
================================================================================

Shape:
Rows    : 1,886,836
Columns : 26

Memory Usage:
1864.16 MB

Columns and Data Types:

                Column Data Type
           Incident_ID    object
         Crime Reports    object
         Crash Reports    object
            Start Time    object
              End Time    object
              Priority     int64
          Initial Type    object
            Close Type    object
               Address    object
                  City    object
                 State    object
                   Zip    object
             Longitude   float64
              Latitude   float64
Police District Number    object
                  Beat    object
                   PRA    object
    CallTime CallRoute   float64
     Calltime Dispatch   float64
       Calltime Arrive   float64
      Calltime Cleared   float64
    CallRoute Dispatch   float64
       Dispatch Arrive   float64
        Arrive Cleared   float64
      Disposition Desc    object
              Location    object

In [8]:
# ==========================================================
# STEP 7 : VIEW SAMPLE RECORDS
# ==========================================================

def display_samples(df, dataset_name, n=5):
    """
    Display the first and last few rows of a dataset.
    """

    print("=" * 80)
    print(f"{dataset_name.upper()} - FIRST {n} ROWS")
    print("=" * 80)

    display(df.head(n))

    print("\n")

    print("=" * 80)
    print(f"{dataset_name.upper()} - LAST {n} ROWS")
    print("=" * 80)

    display(df.tail(n))


# ==========================================================
# CHICAGO DATASET
# ==========================================================

display_samples(chicago_df, "Chicago Crimes")

# ==========================================================
# MONTGOMERY DATASET
# ==========================================================

display_samples(montgomery_df, "Montgomery Police Dispatch")

================================================================================
CHICAGO CRIMES - FIRST 5 ROWS
================================================================================

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,14269678,JK342166,07/20/2026 12:00:00 AM,001XX E WACKER DR,0281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL / MOTEL,False,False,114,1.00,42.00,32.00,02,1177683.00,1902638.00,2026,07/27/2026 03:43:52 PM,41.89,-87.62,"(41.888165132, -87.622937212)"
1,14267487,JK340097,07/20/2026 12:00:00 AM,084XX S MARYLAND AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,False,632,6.00,8.00,44.00,14,1183361.00,1849252.00,2026,07/27/2026 03:43:52 PM,41.74,-87.60,"(41.741539131, -87.603750482)"
2,14267485,JK340089,07/20/2026 12:00:00 AM,105XX S WABASH AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,512,5.00,9.00,49.00,08B,1178438.00,1835166.00,2026,07/27/2026 03:43:52 PM,41.70,-87.62,"(41.70299844, -87.622214313)"
3,14268664,JK341413,07/20/2026 12:00:00 AM,091XX S LAFAYETTE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,634,6.00,9.00,49.00,06,1177542.00,1844332.00,2026,07/27/2026 03:43:52 PM,41.73,-87.63,"(41.728171435, -87.625219193)"
4,14269513,JK342626,07/20/2026 12:00:00 AM,028XX N KIMBALL AVE,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,APARTMENT,False,False,1412,14.00,35.00,21.00,26,1153219.00,1919032.00,2026,07/27/2026 03:43:52 PM,41.93,-87.71,"(41.933672358, -87.712341606)"

================================================================================
CHICAGO CRIMES - LAST 5 ROWS
================================================================================

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
8602729,7548864,HS352185,01/01/2001 12:00:00 AM,016XX N KILDARE AVE,0842,THEFT,AGG: FINANCIAL ID THEFT,RESIDENCE,False,False,2534,25.00,30.00,23.00,06,1147512.00,1910556.00,2001,06/15/2010 01:13:49 AM,41.91,-87.73,"(41.910524926, -87.733532609)"
8602730,7829546,HS637646,01/01/2001 12:00:00 AM,031XX W FULTON BLVD,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,1331,12.00,27.00,27.00,06,1155098.00,1901789.00,2001,12/16/2010 12:38:11 AM,41.89,-87.71,"(41.88631852, -87.705899872)"
8602731,8146039,HT380969,01/01/2001 12:00:00 AM,047XX W MONTANA ST,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,False,True,2521,25.00,31.00,19.00,02,1144295.00,1915861.00,2001,09/07/2021 03:41:02 PM,41.93,-87.75,"(41.925143516, -87.745217143)"
8602732,8175138,HT409754,01/01/2001 12:00:00 AM,111XX S ESMOND ST,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,True,2212,22.00,19.00,75.00,17,1165662.00,1830520.00,2001,09/23/2025 03:41:47 PM,41.69,-87.67,"(41.690529005, -87.669128253)"
8602733,8197725,HT431595,01/01/2001 12:00:00 AM,009XX N HOMAN AVE,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,False,True,1121,11.00,27.00,23.00,02,1153583.00,1905844.00,2001,09/20/2011 12:43:48 AM,41.90,-87.71,"(41.8974761, -87.711355397)"

================================================================================
MONTGOMERY POLICE DISPATCH - FIRST 5 ROWS
================================================================================

,Incident_ID,Crime Reports,Crash Reports,Start Time,End Time,Priority,Initial Type,Close Type,Address,City,State,Zip,Longitude,Latitude,Police District Number,Beat,PRA,CallTime CallRoute,Calltime Dispatch,Calltime Arrive,Calltime Cleared,CallRoute Dispatch,Dispatch Arrive,Arrive Cleared,Disposition Desc,Location
0,P2600225594,NaN,NaN,07/29/2026 12:25:24 AM,07/29/2026 12:35:05 AM,2,TRAFFIC/TRANSPORTATION INCIDENT,TRAFFIC/TRANSPORTATION INCIDENT,18500 BLK BOYSENBERRY DR,GAITHERSBURG,MD,20879,-77.21,39.16,6D,R1,766,225.00,261.00,NaN,581.00,36.00,NaN,NaN,COLOTH-DAMAG-PRKG-HITRUN,POINT (-77.2071 39.1598)
1,P2600225531,NaN,NaN,07/28/2026 10:39:32 PM,07/29/2026 12:32:39 AM,1,"WANTED PERSON, VEHICLE","WANTED PERSON, VEHICLE",10500 BLK CONNECTICUT AVE,KENSINGTON,MD,20895,-77.08,39.03,2D,D1,179,349.00,846.00,1427.00,6787.00,497.00,580.00,5359.00,OTHERMISCELLANEOUS,POINT (-77.0766 39.0275)
2,P2600225569,NaN,NaN,07/28/2026 11:45:58 PM,07/29/2026 12:32:26 AM,1,CDS,CDS,11200 BLK GEORGIA AVE,SILVER SPRING,MD,20902,0.00,0.00,4D,L2,354,298.00,591.00,2101.00,2788.00,292.00,1509.00,687.00,SUSPICIOUSSIT/PRSON/VEH,POINT (0 0)
3,P2600225587,NaN,NaN,07/29/2026 12:12:14 AM,07/29/2026 12:29:40 AM,1,"SUSPICIOUS CIRC, PERSONS, VEHICLE","SUSPICIOUS CIRC, PERSONS, VEHICLE",1100 BLK MAPLE AVE,ROCKVILLE,MD,20851,0.00,0.00,1D,A2,292,191.00,279.00,953.00,1046.00,88.00,674.00,92.00,OTHERMISCELLANEOUS,POINT (0 0)
4,P2600225575,NaN,NaN,07/28/2026 11:55:39 PM,07/29/2026 12:28:49 AM,0,ASLTJA,ASLTJA,1 BLK FEATHERWOOD CT,SILVER SPRING,MD,20904,-76.97,39.06,3D,I1,147,150.00,177.00,356.00,1990.00,26.00,178.00,1633.00,AGGASSLTFRARMSPS/PTNR,POINT (-76.9723 39.0589)

================================================================================
MONTGOMERY POLICE DISPATCH - LAST 5 ROWS
================================================================================

,Incident_ID,Crime Reports,Crash Reports,Start Time,End Time,Priority,Initial Type,Close Type,Address,City,State,Zip,Longitude,Latitude,Police District Number,Beat,PRA,CallTime CallRoute,Calltime Dispatch,Calltime Arrive,Calltime Cleared,CallRoute Dispatch,Dispatch Arrive,Arrive Cleared,Disposition Desc,Location
1886831,P2500213749,250032472,NaN,07/21/2025 10:35:55 AM,NaN,2,STATION RESPONSE,STATION RESPONSE,1000 BLK MILESTONE DR,SILVER SPRING,MD,20904,-76.99,39.05,3D,I1,148,34.00,822.00,1216.00,NaN,787.00,394.00,NaN,MISSINGPERSON,POINT (-76.992 39.0457)
1886832,P2500213768,250032484,NaN,07/21/2025 10:53:04 AM,NaN,3,INDECENCY/LEWDNESS - OCCURRED EARLIER,INDECENCY/LEWDNESS - OCCURRED EARLIER,400 BLK GREENBRIER DR,SILVER SPRING,MD,20910,-77.02,39.00,3D,G2,119,168.00,NaN,NaN,NaN,NaN,NaN,NaN,SEXOFFNS-INDECNTEXPOSR,POINT (-77.0165 39.0041)
1886833,P2500213644,250032456,NaN,07/21/2025 08:38:49 AM,NaN,0,DOMESTIC DISTURBANCE/VIOLENCE,DOMESTIC DISTURBANCE/VIOLENCE,13600 BLK ROBEY RD,SILVER SPRING,MD,20904,0.00,0.00,3D,I2,380,137.00,186.00,817.00,NaN,49.00,630.00,NaN,SIMPLEASSAULTOTRDOMST,POINT (0 0)
1886834,P2500213764,250032489,NaN,07/21/2025 10:49:26 AM,NaN,2,THEFT/LARCENY,THEFT/LARCENY,11100 BLK VEIRS MILL RD,SILVER SPRING,MD,20902,-77.05,39.04,4D,L2,321,161.00,222.00,NaN,NaN,61.00,NaN,NaN,LARCNYSHOPLFTNG$50-$199,POINT (-77.0519 39.0376)
1886835,P2500213767,250032477,NaN,07/21/2025 10:50:46 AM,NaN,1,ASLTOS,ASLTOS,15000 BLK BROSCHART RD,ROCKVILLE,MD,20850,-77.20,39.10,6D,P1,721,217.00,NaN,NaN,NaN,NaN,NaN,NaN,ASSLT,POINT (-77.2003 39.1018)

In [9]:
# ==========================================================
# STEP 8 : MISSING VALUE ANALYSIS
# ==========================================================

def missing_value_summary(df, dataset_name):
    """
    Display missing value statistics for a dataset.
    """

    print("=" * 90)
    print(f"{dataset_name.upper()} - MISSING VALUE ANALYSIS")
    print("=" * 90)

    missing = df.isnull().sum()

    missing = missing[missing > 0]

    if len(missing) == 0:
        print("No missing values found.\n")
        return

    summary = pd.DataFrame({
        "Missing Values": missing,
        "Percentage (%)": (missing / len(df)) * 100
    })

    summary = summary.sort_values(
        by="Missing Values",
        ascending=False
    )

    print(summary)


# ==========================================================
# CHICAGO DATASET
# ==========================================================

missing_value_summary(
    chicago_df,
    "Chicago Crimes"
)

# ==========================================================
# MONTGOMERY DATASET
# ==========================================================

missing_value_summary(
    montgomery_df,
    "Montgomery Police Dispatch"
)

==========================================================================================
CHICAGO CRIMES - MISSING VALUE ANALYSIS
==========================================================================================
                      Missing Values  Percentage (%)
Ward                          614813            7.15
Community Area                613724            7.13
Longitude                      97097            1.13
X Coordinate                   97097            1.13
Y Coordinate                   97097            1.13
Location                       97097            1.13
Latitude                       97097            1.13
Location Description           16380            0.19
District                          47            0.00
==========================================================================================
MONTGOMERY POLICE DISPATCH - MISSING VALUE ANALYSIS
==========================================================================================
                    Missing Values  Percentage (%)
Crash Reports              1823128           96.62
Crime Reports              1550721           82.19
Dispatch Arrive             442608           23.46
Arrive Cleared              430905           22.84
Calltime Arrive             430776           22.83
Calltime Dispatch            81696            4.33
CallRoute Dispatch           81690            4.33
Address                       2777            0.15
Zip                           1273            0.07
City                           842            0.04
State                          409            0.02
Beat                           364            0.02
Calltime Cleared               312            0.02
PRA                            280            0.01
CallTime CallRoute              62            0.00
End Time                        27            0.00
Latitude                        26            0.00
Longitude                       26            0.00
Location                        26            0.00
Disposition Desc                 1            0.00

In [10]:
# ==========================================================
# STEP 9 : DUPLICATE RECORD ANALYSIS
# ==========================================================

def duplicate_summary(df, dataset_name):
    """
    Display duplicate record statistics for a dataset.
    """

    print("=" * 80)
    print(f"{dataset_name.upper()} - DUPLICATE RECORD ANALYSIS")
    print("=" * 80)

    duplicate_count = df.duplicated().sum()
    duplicate_percentage = (duplicate_count / len(df)) * 100

    print(f"Total Rows            : {len(df):,}")
    print(f"Duplicate Rows        : {duplicate_count:,}")
    print(f"Duplicate Percentage  : {duplicate_percentage:.6f}%")
    print()


# ==========================================================
# CHICAGO DATASET
# ==========================================================

duplicate_summary(
    chicago_df,
    "Chicago Crimes"
)

# ==========================================================
# MONTGOMERY DATASET
# ==========================================================

duplicate_summary(
    montgomery_df,
    "Montgomery Police Dispatch"
)

================================================================================
CHICAGO CRIMES - DUPLICATE RECORD ANALYSIS
================================================================================
Total Rows            : 8,602,734
Duplicate Rows        : 0
Duplicate Percentage  : 0.000000%

================================================================================
MONTGOMERY POLICE DISPATCH - DUPLICATE RECORD ANALYSIS
================================================================================
Total Rows            : 1,886,836
Duplicate Rows        : 0
Duplicate Percentage  : 0.000000%

In [11]:
# ==========================================================
# STEP 10 : NUMERICAL DESCRIPTIVE STATISTICS
# ==========================================================

def numerical_summary(df, dataset_name):
    """
    Display descriptive statistics for numerical columns.
    """

    print("=" * 90)
    print(f"{dataset_name.upper()} - NUMERICAL SUMMARY")
    print("=" * 90)

    numeric_df = df.select_dtypes(include=["number"])

    if numeric_df.empty:
        print("No numerical columns found.\n")
        return

    display(numeric_df.describe().T)


# ==========================================================
# CHICAGO DATASET
# ==========================================================

numerical_summary(
    chicago_df,
    "Chicago Crimes"
)

# ==========================================================
# MONTGOMERY DATASET
# ==========================================================

numerical_summary(
    montgomery_df,
    "Montgomery Police Dispatch"
)

==========================================================================================
CHICAGO CRIMES - NUMERICAL SUMMARY
==========================================================================================

                    count       mean        std     min        25%        50%         75%         max
ID             8602734.00 7653885.33 3859784.04  634.00 4150092.50 7651520.50 11105766.00 14275153.00
Beat           8602734.00    1182.77     703.82  111.00     621.00    1034.00     1731.00     2535.00
District       8602687.00      11.29       6.97    1.00       6.00      10.00       17.00       31.00
Ward           7987921.00      22.79      13.86    1.00      10.00      23.00       34.00       50.00
Community Area 7989010.00      37.35      21.54    0.00      23.00      32.00       56.00       77.00
X Coordinate   8505637.00 1164677.41   16937.73    0.00 1153099.00 1166235.00  1176408.00  1205119.00
Y Coordinate   8505637.00 1885939.25   32407.87    0.00 1859228.00 1891059.00  1909415.00  1951622.00
Year           8602734.00    2011.31       7.31 2001.00    2005.00    2010.00     2017.00     2026.00
Latitude       8505637.00      41.84       0.09   36.62      41.77      41.86       41.91       42.02
Longitude      8505637.00     -87.67       0.06  -91.69     -87.71     -87.67      -87.63      -87.52

==========================================================================================
MONTGOMERY POLICE DISPATCH - NUMERICAL SUMMARY
==========================================================================================

                        count    mean     std    min     25%     50%     75%       max
Priority           1886836.00    1.86    1.26   0.00    1.00    1.00    3.00      5.00
Longitude          1886810.00  -73.16   17.01 -81.53  -77.19  -77.11  -77.03      0.00
Latitude           1886810.00   37.08    8.62   0.00   39.02   39.08   39.14     39.35
CallTime CallRoute 1886774.00  161.54  194.47   0.00   88.00  130.00  194.00  81641.00
Calltime Dispatch  1805140.00  882.70 1869.68   0.00  213.00  363.00  766.00 353322.00
Calltime Arrive    1456060.00 1431.57 2059.86   0.00  589.00  947.00 1626.00 361815.00
Calltime Cleared   1886524.00 3254.50 4799.14   0.00 1254.00 2172.00 3916.00 416447.00
CallRoute Dispatch 1805146.00  719.87 1856.17   0.00   71.00  190.00  564.00 353224.00
Dispatch Arrive    1444228.00  707.45 1443.20   0.00  252.00  473.00  834.00 358357.00
Arrive Cleared     1455931.00 1882.99 3879.04   0.00  376.00  876.00 2061.00 415727.00

In [12]:
# ==========================================================
# STEP 11 : CATEGORICAL COLUMN ANALYSIS
# ==========================================================

def categorical_summary(df, dataset_name, max_examples=10):
    """
    Display information about categorical columns.
    """

    print("=" * 100)
    print(f"{dataset_name.upper()} - CATEGORICAL COLUMN ANALYSIS")
    print("=" * 100)

    categorical_cols = df.select_dtypes(include=["object", "category"]).columns

    for col in categorical_cols:
        print(f"\nColumn: {col}")
        print(f"Unique Values: {df[col].nunique(dropna=True):,}")

        examples = df[col].dropna().unique()[:max_examples]

        print("Example Values:")
        for value in examples:
            print(f"  - {value}")

        print("-" * 60)


# ==========================================================
# CHICAGO DATASET
# ==========================================================

categorical_summary(chicago_df, "Chicago Crimes")

# ==========================================================
# MONTGOMERY DATASET
# ==========================================================

categorical_summary(montgomery_df, "Montgomery Police Dispatch")

====================================================================================================
CHICAGO CRIMES - CATEGORICAL COLUMN ANALYSIS
====================================================================================================

Column: Case Number
Unique Values: 8,602,108
Example Values:
  - JK342166
  - JK340097
  - JK340089
  - JK341413
  - JK342626
  - JK340493
  - JK341071
  - JK340695
  - JK342143
  - JK341815
------------------------------------------------------------

Column: Date
Unique Values: 3,614,319
Example Values:
  - 07/20/2026 12:00:00 AM
  - 07/19/2026 11:55:00 PM
  - 07/19/2026 11:52:00 PM
  - 07/19/2026 11:50:00 PM
  - 07/19/2026 11:48:00 PM
  - 07/19/2026 11:46:00 PM
  - 07/19/2026 11:45:00 PM
  - 07/19/2026 11:43:00 PM
  - 07/19/2026 11:42:00 PM
  - 07/19/2026 11:40:00 PM
------------------------------------------------------------

Column: Block
Unique Values: 66,019
Example Values:
  - 001XX E WACKER DR
  - 084XX S MARYLAND AVE
  - 105XX S WABASH AVE
  - 091XX S LAFAYETTE AVE
  - 028XX N KIMBALL AVE
  - 001XX N WOLCOTT AVE
  - 064XX S EBERHART AVE
  - 082XX S HERMITAGE AVE
  - 068XX S CLYDE AVE
  - 029XX N CLYBOURN AVE
------------------------------------------------------------

Column: IUCR
Unique Values: 418
Example Values:
  - 0281
  - 1310
  - 0486
  - 0810
  - 4387
  - 2820
  - 0560
  - 0820
  - 1320
  - 0920
------------------------------------------------------------

Column: Primary Type
Unique Values: 34
Example Values:
  - CRIMINAL SEXUAL ASSAULT
  - CRIMINAL DAMAGE
  - BATTERY
  - THEFT
  - OTHER OFFENSE
  - ASSAULT
  - MOTOR VEHICLE THEFT
  - SEX OFFENSE
  - BURGLARY
  - NARCOTICS
------------------------------------------------------------

Column: Description
Unique Values: 570
Example Values:
  - NON-AGGRAVATED
  - TO PROPERTY
  - DOMESTIC BATTERY SIMPLE
  - OVER $500
  - VIOLATE ORDER OF PROTECTION
  - TELEPHONE THREAT
  - SIMPLE
  - $500 AND UNDER
  - TO VEHICLE
  - ATTEMPT - AUTOMOBILE
------------------------------------------------------------

Column: Location Description
Unique Values: 218
Example Values:
  - HOTEL / MOTEL
  - RESIDENCE
  - APARTMENT
  - DRIVEWAY - RESIDENTIAL
  - PARKING LOT / GARAGE (NON RESIDENTIAL)
  - STREET
  - SIDEWALK
  - VEHICLE NON-COMMERCIAL
  - PARK PROPERTY
  - GAS STATION
------------------------------------------------------------

Column: FBI Code
Unique Values: 26
Example Values:
  - 02
  - 14
  - 08B
  - 06
  - 26
  - 08A
  - 07
  - 17
  - 05
  - 18
------------------------------------------------------------

Column: Updated On
Unique Values: 7,827
Example Values:
  - 07/27/2026 03:43:52 PM
  - 07/26/2026 03:49:04 PM
  - 07/27/2026 03:42:38 PM
  - 07/25/2026 04:47:30 PM
  - 07/26/2026 03:47:55 PM
  - 07/25/2026 04:46:21 PM
  - 07/23/2026 04:10:20 PM
  - 07/22/2026 03:43:05 PM
  - 07/23/2026 04:07:48 PM
  - 07/21/2026 03:48:08 PM
------------------------------------------------------------

Column: Location
Unique Values: 914,699
Example Values:
  - (41.888165132, -87.622937212)
  - (41.741539131, -87.603750482)
  - (41.70299844, -87.622214313)
  - (41.728171435, -87.625219193)
  - (41.933672358, -87.712341606)
  - (41.884514051, -87.674276601)
  - (41.777696923, -87.613147985)
  - (41.744335196, -87.666932369)
  - (41.770976444, -87.573983875)
  - (41.933585796, -87.679931214)
------------------------------------------------------------
====================================================================================================
MONTGOMERY POLICE DISPATCH - CATEGORICAL COLUMN ANALYSIS
====================================================================================================

Column: Incident_ID
Unique Values: 1,886,836
Example Values:
  - P2600225594
  - P2600225531
  - P2600225569
  - P2600225587
  - P2600225575
  - P2600225580
  - P2600225584
  - P2600225552
  - P2600225526
  - P2600225571
------------------------------------------------------------

Column: Crime Reports
Unique Values: 336,115
Example Values:
  - 260033143
  - 260033147
  - 260033140
  - 260033144
  - 260033142
  - 260033135
  - 260033118
  - 260033132
  - 260033134
  - 260033125
------------------------------------------------------------

Column: Crash Reports
Unique Values: 63,708
Example Values:
  - 260032958
  - 260032867
  - 260032861
  - 260032849
  - 260032831
  - 260032823
  - 260032818
  - 260032783
  - 260032760
  - 260032741
------------------------------------------------------------

Column: Start Time
Unique Values: 1,880,055
Example Values:
  - 07/29/2026 12:25:24 AM
  - 07/28/2026 10:39:32 PM
  - 07/28/2026 11:45:58 PM
  - 07/29/2026 12:12:14 AM
  - 07/28/2026 11:55:39 PM
  - 07/28/2026 11:54:10 PM
  - 07/29/2026 12:04:41 AM
  - 07/28/2026 11:20:08 PM
  - 07/28/2026 10:36:28 PM
  - 07/28/2026 11:50:18 PM
------------------------------------------------------------

Column: End Time
Unique Values: 1,879,722
Example Values:
  - 07/29/2026 12:35:05 AM
  - 07/29/2026 12:32:39 AM
  - 07/29/2026 12:32:26 AM
  - 07/29/2026 12:29:40 AM
  - 07/29/2026 12:28:49 AM
  - 07/29/2026 12:22:51 AM
  - 07/29/2026 12:20:41 AM
  - 07/29/2026 12:20:34 AM
  - 07/29/2026 12:17:43 AM
  - 07/29/2026 12:17:22 AM
------------------------------------------------------------

Column: Initial Type
Unique Values: 234
Example Values:
  - TRAFFIC/TRANSPORTATION INCIDENT
  - WANTED PERSON, VEHICLE
  - CDS
  - SUSPICIOUS CIRC, PERSONS, VEHICLE
  - ASLTJA
  - ADMINISTRATIVE (DOCUMENT, LOST OR FOUND PROPERTY, MESSAGES,
  - TRAFFIC VIOLATION
  - ASSAULT
  - NOISE - NOISE - OTHER COMPLAINTS
  - BOX ALARM - VIA FRS
------------------------------------------------------------

Column: Close Type
Unique Values: 238
Example Values:
  - TRAFFIC/TRANSPORTATION INCIDENT
  - WANTED PERSON, VEHICLE
  - CDS
  - SUSPICIOUS CIRC, PERSONS, VEHICLE
  - ASLTJA
  - ADMINISTRATIVE (DOCUMENT, LOST OR FOUND PROPERTY, MESSAGES,
  - TRAFFIC VIOLATION
  - ASSAULT
  - NOISE - NOISE - OTHER COMPLAINTS
  - BOX ALARM - VIA FRS
------------------------------------------------------------

Column: Address
Unique Values: 49,027
Example Values:
  - 18500 BLK  BOYSENBERRY DR
  - 10500 BLK  CONNECTICUT AVE
  - 11200 BLK  GEORGIA AVE
  - 1100 BLK  MAPLE AVE
  - 1  BLK  FEATHERWOOD CT
  - 9000 BLK  WALDEN RD
  - 2800 BLK  UNIVERSITY BLVD W
  - KNOWLES AVE / BEACH DR
  - 7200 BLK  WISCONSIN AVE
  - 1  BLK  FIRSTFIELD RD
------------------------------------------------------------

Column: City
Unique Values: 95
Example Values:
  - GAITHERSBURG
  - KENSINGTON
  - SILVER SPRING
  - ROCKVILLE
  - BETHESDA
  - BROOKEVILLE
  - MONTGOMERY VILLAGE
  - GERMANTOWN
  - BOYDS
  - BURTONSVILLE
------------------------------------------------------------

Column: State
Unique Values: 5
Example Values:
  - MD
  - DC
  - VA
  - DCMD
  - MDDC
------------------------------------------------------------

Column: Zip
Unique Values: 248
Example Values:
  - 20879
  - 20895
  - 20902
  - 20851
  - 20904
  - 20901
  - 20814
  - 20878
  - 20877
  - 20853
------------------------------------------------------------

Column: Police District Number
Unique Values: 9
Example Values:
  - 6D
  - 2D
  - 4D
  - 1D
  - 3D
  - 5D
  - OOC
  - PCW
  - TRU
------------------------------------------------------------

Column: Beat
Unique Values: 45
Example Values:
  - R1
  - D1
  - L2
  - A2
  - I1
  - G2
  - D2
  - P2
  - P3
  - K1
------------------------------------------------------------

Column: PRA
Unique Values: 812
Example Values:
  - 766
  - 179
  - 354
  - 292
  - 147
  - 124
  - 319
  - 181
  - 033
  - 554
------------------------------------------------------------

Column: Disposition Desc
Unique Values: 495
Example Values:
  - COLOTH-DAMAG-PRKG-HITRUN
  - OTHERMISCELLANEOUS
  - SUSPICIOUSSIT/PRSON/VEH
  - AGGASSLTFRARMSPS/PTNR
  - DISABLEDMOTORVEHICLE
  - TRAFFICHAZARD
  - DRIVINGUNDR
  - TRESPASSING
  - DISORDERLYCONDUCT
  - FIREOTHER
------------------------------------------------------------

Column: Location
Unique Values: 67,214
Example Values:
  - POINT (-77.2071 39.1598)
  - POINT (-77.0766 39.0275)
  - POINT (0 0)
  - POINT (-76.9723 39.0589)
  - POINT (-77.0033 39.0036)
  - POINT (-77.0571 39.039)
  - POINT (-77.0861 39.031)
  - POINT (-77.0928 38.9812)
  - POINT (-77.2237 39.1437)
  - POINT (-77.1971 39.141)
------------------------------------------------------------

In [13]:
# ==========================================================
# STEP 12 : DATA CLEANING PIPELINE SKELETON
# ==========================================================

def clean_missing_values(df):
    """
    Handle missing values.
    (Implementation will be added in the next steps.)
    """
    return df


def convert_data_types(df):
    """
    Convert columns to appropriate data types.
    """
    return df


def standardize_text(df):
    """
    Standardize text formatting.
    """
    return df


def clean_coordinates(df):
    """
    Handle invalid coordinate values.
    """
    return df


def optimize_memory(df):
    """
    Reduce memory usage by optimizing data types.
    """
    return df


def data_cleaning_pipeline(df):
    """
    Execute all cleaning steps in sequence.
    """

    print("Starting data cleaning pipeline...")

    df = clean_missing_values(df)
    df = convert_data_types(df)
    df = standardize_text(df)
    df = clean_coordinates(df)
    df = optimize_memory(df)

    print("Data cleaning pipeline completed.")

    return df


print("=" * 70)
print("DATA CLEANING PIPELINE CREATED SUCCESSFULLY")
print("=" * 70)

======================================================================
DATA CLEANING PIPELINE CREATED SUCCESSFULLY
======================================================================

In [16]:
from pathlib import Path

# ==========================================================
# PROJECT PATHS
# ==========================================================

PROJECT_ROOT = "/content/drive/MyDrive/Army_Provost_ML_Project"

RAW_DATASET_PATH = f"{PROJECT_ROOT}/Datasets/Raw"
CLEAN_DATASET_PATH = f"{PROJECT_ROOT}/Datasets/Cleaned"

MODEL_PATH = f"{PROJECT_ROOT}/Models"
FIGURE_PATH = f"{PROJECT_ROOT}/Figures"
REPORTS_PATH = f"{PROJECT_ROOT}/Reports"
OUTPUTS_PATH = f"{PROJECT_ROOT}/Outputs"
LOGS_PATH = f"{PROJECT_ROOT}/Logs"

print("REPORTS PATH")
print(REPORTS_PATH)

REPORTS PATH
/content/drive/MyDrive/Army_Provost_ML_Project/Reports

In [17]:
# ==========================================================
# STEP 12 : DATA QUALITY REPORT
# ==========================================================

import pandas as pd
import os

def generate_data_quality_report(df, dataset_name, save_path):
    """
    Generates a comprehensive data quality report.
    """

    report = pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.astype(str).values,
        "Missing Values": df.isnull().sum().values,
        "Missing (%)": ((df.isnull().sum() / len(df)) * 100).round(2).values,
        "Unique Values": df.nunique(dropna=True).values
    })

    report["Memory Usage (MB)"] = [
        round(df[col].memory_usage(deep=True) / (1024 ** 2), 2)
        for col in df.columns
    ]

    print("=" * 80)
    print(f"{dataset_name} DATA QUALITY REPORT")
    print("=" * 80)

    display(report)

    # Save report as CSV
    filename = os.path.join(
        save_path,
        f"{dataset_name.lower().replace(' ', '_')}_data_quality_report.csv"
    )

    report.to_csv(filename, index=False)

    print("\nReport saved to:")
    print(filename)

    return report


# ----------------------------------------------------------
# Generate reports
# ----------------------------------------------------------

chicago_report = generate_data_quality_report(
    chicago_df,
    "Chicago Crimes",
    REPORTS_PATH
)

montgomery_report = generate_data_quality_report(
    montgomery_df,
    "Montgomery Dispatch",
    REPORTS_PATH
)

================================================================================
Chicago Crimes DATA QUALITY REPORT
================================================================================

                  Column Data Type  Missing Values  Missing (%)  Unique Values  Memory Usage (MB)
0                     ID     int64               0         0.00        8602734              65.63
1            Case Number    object               0         0.00        8602108             467.18
2                   Date    object               0         0.00        3614319             582.50
3                  Block    object               0         0.00          66019             553.28
4                   IUCR    object               0         0.00            418             434.82
5           Primary Type    object               0         0.00             34             484.79
6            Description    object               0         0.00            570             535.77
7   Location Description    object           16380         0.19            218             494.10
8                 Arrest      bool               0         0.00              2               8.20
9               Domestic      bool               0         0.00              2               8.20
10                  Beat     int64               0         0.00            305              65.63
11              District   float64              47         0.00             24              65.63
12                  Ward   float64          614813         7.15             50              65.63
13        Community Area   float64          613724         7.13             78              65.63
14              FBI Code    object               0         0.00             26             420.66
15          X Coordinate   float64           97097         1.13          79404              65.63
16          Y Coordinate   float64           97097         1.13         130473              65.63
17                  Year     int64               0         0.00             26              65.63
18            Updated On    object               0         0.00           7827             582.50
19              Latitude   float64           97097         1.13         913363              65.63
20             Longitude   float64           97097         1.13         912770              65.63
21              Location    object           97097         1.13         914699             633.89

Report saved to:
/content/drive/MyDrive/Army_Provost_ML_Project/Reports/chicago_crimes_data_quality_report.csv
================================================================================
Montgomery Dispatch DATA QUALITY REPORT
================================================================================

                    Column Data Type  Missing Values  Missing (%)  Unique Values  Memory Usage (MB)
0              Incident_ID    object               0         0.00        1886836             107.97
1            Crime Reports    object         1550721        82.19         336115              65.93
2            Crash Reports    object         1823128        96.62          63708              59.16
3               Start Time    object               0         0.00        1880055             127.76
4                 End Time    object              27         0.00        1879722             127.76
5                 Priority     int64               0         0.00              6              14.40
6             Initial Type    object               0         0.00            234             138.50
7               Close Type    object               0         0.00            238             138.58
8                  Address    object            2777         0.15          49027             130.08
9                     City    object             842         0.04             95             107.97
10                   State    object             409         0.02              5              91.76
11                     Zip    object            1273         0.07            248              97.14
12               Longitude   float64              26         0.00          19795              14.40
13                Latitude   float64              26         0.00          41507              14.40
14  Police District Number    object               0         0.00              9              91.77
15                    Beat    object             364         0.02             45              91.76
16                     PRA    object             280         0.01            812              93.56
17      CallTime CallRoute   float64              62         0.00           2717              14.40
18       Calltime Dispatch   float64           81696         4.33          16592              14.40
19         Calltime Arrive   float64          430776        22.83          14514              14.40
20        Calltime Cleared   float64             312         0.02          28511              14.40
21      CallRoute Dispatch   float64           81690         4.33          16354              14.40
22         Dispatch Arrive   float64          442608        23.46           9540              14.40
23          Arrive Cleared   float64          430905        22.84          24244              14.40
24        Disposition Desc    object               1         0.00            495             120.74
25                Location    object              26         0.00          67214             129.77

Report saved to:
/content/drive/MyDrive/Army_Provost_ML_Project/Reports/montgomery_dispatch_data_quality_report.csv

In [18]:
# ==========================================================
# SECTION 5 : DATA CLEANING
# STEP 13 : CONVERT DATE COLUMNS TO DATETIME
# ==========================================================

print("=" * 80)
print("CONVERTING DATE COLUMNS")
print("=" * 80)

# ----------------------------------------------------------
# Chicago Crimes Dataset
# ----------------------------------------------------------

print("\nChicago Crimes Dataset")

chicago_df["Date"] = pd.to_datetime(
    chicago_df["Date"],
    errors="coerce"
)

chicago_df["Updated On"] = pd.to_datetime(
    chicago_df["Updated On"],
    errors="coerce"
)

print("✓ Date converted")
print("✓ Updated On converted")

# ----------------------------------------------------------
# Montgomery Dispatch Dataset
# ----------------------------------------------------------

print("\nMontgomery Dispatch Dataset")

montgomery_df["Start Time"] = pd.to_datetime(
    montgomery_df["Start Time"],
    errors="coerce"
)

montgomery_df["End Time"] = pd.to_datetime(
    montgomery_df["End Time"],
    errors="coerce"
)

print("✓ Start Time converted")
print("✓ End Time converted")

print("\n")
print("=" * 80)
print("DATETIME CONVERSION COMPLETED")
print("=" * 80)

================================================================================
CONVERTING DATE COLUMNS
================================================================================

Chicago Crimes Dataset
✓ Date converted
✓ Updated On converted

Montgomery Dispatch Dataset
✓ Start Time converted
✓ End Time converted


================================================================================
DATETIME CONVERSION COMPLETED
================================================================================

In [19]:
# ==========================================================
# VERIFY DATETIME CONVERSION
# ==========================================================

print("=" * 80)
print("CHICAGO DATA TYPES")
print("=" * 80)

print(chicago_df[["Date", "Updated On"]].dtypes)

print("\n")

print("=" * 80)
print("MONTGOMERY DATA TYPES")
print("=" * 80)

print(montgomery_df[["Start Time", "End Time"]].dtypes)

================================================================================
CHICAGO DATA TYPES
================================================================================
Date          datetime64[ns]
Updated On    datetime64[ns]
dtype: object


================================================================================
MONTGOMERY DATA TYPES
================================================================================
Start Time    datetime64[ns]
End Time      datetime64[ns]
dtype: object

In [20]:
# ==========================================================
# SECTION 5 : DATA CLEANING
# STEP 14 : CLEAN INVALID COORDINATES
# ==========================================================

import numpy as np

print("=" * 80)
print("CLEANING INVALID COORDINATES")
print("=" * 80)

# ----------------------------------------------------------
# Count invalid coordinates BEFORE cleaning
# ----------------------------------------------------------

invalid_lat_before = (montgomery_df["Latitude"] == 0).sum()
invalid_lon_before = (montgomery_df["Longitude"] == 0).sum()

print("\nMontgomery Dataset")
print(f"Invalid Latitude values  : {invalid_lat_before:,}")
print(f"Invalid Longitude values : {invalid_lon_before:,}")

# ----------------------------------------------------------
# Replace invalid coordinates with NaN
# ----------------------------------------------------------

montgomery_df["Latitude"] = montgomery_df["Latitude"].replace(0, np.nan)
montgomery_df["Longitude"] = montgomery_df["Longitude"].replace(0, np.nan)

# ----------------------------------------------------------
# Count invalid coordinates AFTER cleaning
# ----------------------------------------------------------

invalid_lat_after = (montgomery_df["Latitude"] == 0).sum()
invalid_lon_after = (montgomery_df["Longitude"] == 0).sum()

print("\nAfter Cleaning")

print(f"Invalid Latitude values  : {invalid_lat_after:,}")
print(f"Invalid Longitude values : {invalid_lon_after:,}")

print("\nCoordinate cleaning completed successfully.")

================================================================================
CLEANING INVALID COORDINATES
================================================================================

Montgomery Dataset
Invalid Latitude values  : 96,793
Invalid Longitude values : 96,793

After Cleaning
Invalid Latitude values  : 0
Invalid Longitude values : 0

Coordinate cleaning completed successfully.

In [21]:
# ==========================================================
# VERIFY COORDINATE CLEANING
# ==========================================================

print("=" * 80)
print("VERIFYING MISSING COORDINATES")
print("=" * 80)

print(montgomery_df[["Latitude", "Longitude"]].isnull().sum())

================================================================================
VERIFYING MISSING COORDINATES
================================================================================
Latitude     96819
Longitude    96819
dtype: int64